// Generated by scripts/build-main.js. Edit src/ files instead.
const __modules = {
"src/cli/args.js": function(module, exports, __require) {
function parseArgsTemplate(template, prompt, defaultArgs) {
  const tokens = [];
  const source = template || defaultArgs;
  let current = "";
  let quote = null;

  for (let index = 0; index < source.length; index += 1) {
    const char = source[index];

    if ((char === "\"" || char === "'") && !quote) {
      quote = char;
      continue;
    }

    if (char === quote) {
      quote = null;
      continue;
    }

    if (/\s/.test(char) && !quote) {
      if (current) {
        tokens.push(current);
        current = "";
      }
      continue;
    }

    current += char;
  }

  if (current) {
    tokens.push(current);
  }

  return tokens.map((token) => token.replace(/\{\{prompt\}\}/g, prompt));
}

function withOutputLastMessage(args, outputPath) {
  if (!args.includes("-o") && !args.includes("--output-last-message")) {
    const execIndex = args.indexOf("exec");
    if (execIndex >= 0) {
      return [
        ...args.slice(0, execIndex + 1),
        "--output-last-message",
        outputPath,
        ...args.slice(execIndex + 1)
      ];
    }
  }

  return args;
}

function withJsonOutput(args) {
  if (args.includes("--json")) {
    return args;
  }

  const execIndex = args.indexOf("exec");
  if (execIndex >= 0) {
    return [
      ...args.slice(0, execIndex + 1),
      "--json",
      ...args.slice(execIndex + 1)
    ];
  }

  return args;
}

module.exports = {
  parseArgsTemplate,
  withJsonOutput,
  withOutputLastMessage
};

},
"src/cli/env.js": function(module, exports, __require) {
function buildCliPath(existingPath) {
  const pathParts = [
    "/opt/homebrew/bin",
    "/usr/local/bin",
    "/usr/bin",
    "/bin",
    "/usr/sbin",
    "/sbin"
  ];

  for (const part of (existingPath || "").split(":")) {
    if (part && !pathParts.includes(part)) {
      pathParts.push(part);
    }
  }

  return pathParts.join(":");
}

module.exports = {
  buildCliPath
};

},
"src/cli/shell.js": function(module, exports, __require) {
function shellQuote(value) {
  return `'${String(value).replace(/'/g, "'\\''")}'`;
}

function escapeAppleScriptString(value) {
  return String(value)
    .replace(/\\/g, "\\\\")
    .replace(/"/g, "\\\"");
}

module.exports = {
  escapeAppleScriptString,
  shellQuote
};

},
"src/modes.js": function(module, exports, __require) {
const MODE_OPTIONS = {
  readOnly: {
    label: "Read only",
    description: "Inspect vault files but do not write.",
    args: ["--sandbox", "read-only"]
  },
  workspaceWrite: {
    label: "Workspace write",
    description: "Allow edits inside the vault or working directory.",
    args: ["--sandbox", "workspace-write", "--skip-git-repo-check"]
  },
  fullAccess: {
    label: "Full access",
    description: "Allow broad local access. Use carefully.",
    args: ["--sandbox", "danger-full-access", "--skip-git-repo-check"]
  }
};

function applyModeArgs(args, mode, defaultMode) {
  const modeConfig = MODE_OPTIONS[mode] || MODE_OPTIONS[defaultMode];
  const execIndex = args.indexOf("exec");
  if (execIndex < 0) {
    return args;
  }

  const additions = [];
  const hasSandbox = args.includes("--sandbox") || args.includes("-s");
  const hasDangerBypass = args.includes("--dangerously-bypass-approvals-and-sandbox");
  const hasSkipGitRepoCheck = args.includes("--skip-git-repo-check");

  for (let index = 0; index < modeConfig.args.length; index += 1) {
    const flag = modeConfig.args[index];
    const value = modeConfig.args[index + 1];

    if (flag === "--sandbox") {
      if (!hasSandbox && !hasDangerBypass) {
        additions.push(flag, value);
      }
      index += 1;
      continue;
    }

    if (flag === "--skip-git-repo-check" && !hasSkipGitRepoCheck) {
      additions.push(flag);
    }
  }

  return [
    ...args.slice(0, execIndex + 1),
    ...additions,
    ...args.slice(execIndex + 1)
  ];
}

function getModeDescription(mode, defaultMode) {
  return (MODE_OPTIONS[mode] || MODE_OPTIONS[defaultMode]).description;
}

module.exports = {
  MODE_OPTIONS,
  applyModeArgs,
  getModeDescription
};

},
"src/prompt.js": function(module, exports, __require) {
async function buildPrompt(app, settings, prompt, conversation) {
  const result = await buildPromptWithMetadata(app, settings, prompt, conversation);
  return result.prompt;
}

async function buildPromptWithMetadata(app, settings, prompt, conversation) {
  const promptParts = [];
  const contextLimit = Number(settings.contextLimitChars) || 258000;

  if (!settings.includeActiveNote) {
    promptParts.push(formatConversationPrompt(prompt, conversation, contextLimit));
    return buildPromptResult(promptParts.join("\n"), contextLimit);
  }

  const file = app.workspace.getActiveFile();
  if (!file) {
    promptParts.push(formatConversationPrompt(prompt, conversation, contextLimit));
    return buildPromptResult(promptParts.join("\n"), contextLimit);
  }

  const note = await app.vault.cachedRead(file);
  const maxChars = Number(settings.activeNoteMaxChars) || 6000;
  const clippedNote = note.length > maxChars
    ? `${note.slice(0, maxChars)}\n\n[Note clipped]`
    : note;

  const notePrompt = [
    `Active Obsidian note: ${file.path}`,
    "",
    clippedNote,
    ""
  ].join("\n");
  const conversationBudget = Math.max(1000, contextLimit - notePrompt.length);

  promptParts.push(
    notePrompt,
    formatConversationPrompt(prompt, conversation, conversationBudget)
  );

  return buildPromptResult(promptParts.join("\n"), contextLimit);
}

function formatConversationPrompt(prompt, conversation, maxChars) {
  if (!conversation || conversation.length <= 1) {
    return ["User request:", prompt].join("\n");
  }

  const transcript = formatConversationTranscript(conversation, maxChars);

  return [
    "Conversation so far:",
    transcript,
    "",
    "Respond to the latest user request."
  ].join("\n");
}

function formatConversationTranscript(conversation, maxChars) {
  const fullTranscript = conversation.map(formatMessageForTranscript).join("\n\n");
  if (!maxChars || fullTranscript.length <= maxChars) {
    return fullTranscript;
  }

  const latestMessage = conversation[conversation.length - 1];
  const latestText = formatMessageForTranscript(latestMessage);
  const summaryHeader = `[Earlier conversation compressed because it exceeded the context character limit. Original messages: ${conversation.length - 1}.]`;
  const availableForRecent = Math.max(0, maxChars - latestText.length - summaryHeader.length - 8);
  const recentMessages = [];
  let used = 0;

  for (let index = conversation.length - 2; index >= 0; index -= 1) {
    const formatted = formatMessageForTranscript(conversation[index]);
    const nextUsed = used + formatted.length + (recentMessages.length > 0 ? 2 : 0);
    if (nextUsed > availableForRecent) {
      break;
    }
    recentMessages.unshift(formatted);
    used = nextUsed;
  }

  const omittedCount = Math.max(0, conversation.length - 1 - recentMessages.length);
  const compressedSummary = summarizeMessages(conversation.slice(0, omittedCount), summaryHeader);
  const compressedTranscript = [
    compressedSummary,
    recentMessages.join("\n\n"),
    latestText
  ].filter(Boolean).join("\n\n");

  return limitCompressedTranscript(compressedTranscript, latestText, maxChars);
}

function summarizeMessages(messages, header) {
  if (messages.length === 0) {
    return "";
  }

  const maxSummaryChars = 12000;
  const lines = [header];
  let used = header.length;

  for (const message of messages) {
    const content = compactText(message.content);
    const line = `- ${message.role === "user" ? "User" : "Agent"}: ${truncateText(content, 500)}`;
    if (used + line.length + 1 > maxSummaryChars) {
      lines.push(`- ... ${messages.length - lines.length + 1} earlier messages omitted`);
      break;
    }
    lines.push(line);
    used += line.length + 1;
  }

  return lines.join("\n");
}

function formatMessageForTranscript(message) {
  return `${message.role === "user" ? "User" : "Agent"}: ${message.content}`;
}

function compactText(text) {
  return String(text || "").replace(/\s+/g, " ").trim();
}

function truncateText(text, maxChars) {
  if (text.length <= maxChars) {
    return text;
  }
  if (maxChars <= 3) {
    return text.slice(0, maxChars);
  }
  return `${text.slice(0, maxChars - 3)}...`;
}

function limitCompressedTranscript(transcript, latestText, maxChars) {
  if (!maxChars || transcript.length <= maxChars) {
    return transcript;
  }

  if (latestText.length >= maxChars) {
    return truncateText(latestText, maxChars);
  }

  const prefixBudget = Math.max(0, maxChars - latestText.length - 2);
  const prefix = truncateText(transcript.slice(0, transcript.length - latestText.length), prefixBudget);
  return [prefix, latestText].filter(Boolean).join("\n\n");
}

function limitPrompt(prompt, maxChars) {
  if (!maxChars || prompt.length <= maxChars) {
    return prompt;
  }

  const notice = "[Prompt compressed to fit the configured context character limit.]\n\n";
  const available = Math.max(0, maxChars - notice.length);
  if (available === 0) {
    return notice.slice(0, maxChars);
  }
  return `${notice}${prompt.slice(prompt.length - available)}`;
}

function buildPromptResult(rawPrompt, contextLimit) {
  const prompt = limitPrompt(rawPrompt, contextLimit);
  return {
    prompt,
    context: {
      limitChars: contextLimit,
      originalChars: rawPrompt.length,
      promptChars: prompt.length,
      compressed: prompt.length < rawPrompt.length || rawPrompt.includes("[Earlier conversation compressed")
    }
  };
}

module.exports = {
  buildPrompt,
  buildPromptWithMetadata
};

},
"src/settings.js": function(module, exports, __require) {
const { MODE_OPTIONS } = __require("src/modes.js");

const DEFAULT_SETTINGS = {
  agentId: "codex",
  codexPath: "/opt/homebrew/bin/codex",
  args: "exec {{prompt}}",
  interactiveArgs: "",
  mode: "readOnly",
  workingDirectory: "",
  includeActiveNote: true,
  debugActivity: false,
  activeNoteMaxChars: 6000,
  contextLimitChars: 258000
};

function normalizeSettings(savedSettings) {
  const settings = Object.assign({}, DEFAULT_SETTINGS, savedSettings || {});

  if (savedSettings && savedSettings.command && !savedSettings.codexPath) {
    settings.codexPath = savedSettings.command;
  }

  if (settings.mode === "ask") {
    settings.mode = "readOnly";
  }

  if (!MODE_OPTIONS[settings.mode]) {
    settings.mode = DEFAULT_SETTINGS.mode;
  }

  if (!settings.agentId) {
    settings.agentId = DEFAULT_SETTINGS.agentId;
  }

  settings.activeNoteMaxChars = normalizePositiveInteger(
    settings.activeNoteMaxChars,
    DEFAULT_SETTINGS.activeNoteMaxChars
  );
  settings.contextLimitChars = normalizePositiveInteger(
    settings.contextLimitChars,
    DEFAULT_SETTINGS.contextLimitChars
  );

  delete settings.command;
  return settings;
}

function normalizePositiveInteger(value, fallback) {
  const parsed = Number.parseInt(value, 10);
  return Number.isFinite(parsed) && parsed > 0 ? parsed : fallback;
}

module.exports = {
  DEFAULT_SETTINGS,
  normalizeSettings
};

},
"src/agents/codex/jsonEvents.js": function(module, exports, __require) {
function codexJsonEventToUpdates(event) {
  if (!event || typeof event !== "object") {
    return [];
  }

  const type = event.type || "event";
  const item = event.item;

  if (type === "error") {
    return [{ kind: "error", title: "Error", detail: extractText(event) || compactJson(event) }];
  }

  if (type === "thread.started") {
    return [{ kind: "activity", title: "Thread started", detail: event.thread_id || "" }];
  }

  if (type === "turn.started") {
    return [{ kind: "activity", title: "Turn started", detail: "" }];
  }

  if (type === "turn.completed") {
    return [{ kind: "activity", title: "Turn completed", detail: formatUsage(event.usage) }];
  }

  if (type === "turn.failed") {
    return [{ kind: "error", title: "Turn failed", detail: extractText(event) || compactJson(event) }];
  }

  if (!item || typeof item !== "object") {
    return [{ kind: "activity", title: type, detail: compactJson(event) }];
  }

  if (item.type === "agent_message") {
    const text = extractText(item);
    return text ? [{ kind: "content", text }] : [];
  }

  if (item.type === "reasoning") {
    return [{
      kind: "reasoning",
      title: type === "item.started" ? "Thinking..." : "Thinking",
      detail: extractText(item) || summarizeItem(item)
    }];
  }

  if (item.type === "command_execution") {
    return [{
      kind: "tool",
      title: formatCommandTitle(type, item),
      summary: formatCommandSummary(item),
      detail: formatCommandExecution(item)
    }];
  }

  if (isToolItem(item)) {
    const summary = extractText(item) || summarizeItem(item);
    return [{
      kind: "tool",
      title: formatEventTitle(type, formatToolTitle(item)),
      summary: compactOneLine(summary),
      detail: summary
    }];
  }

  if (item.type === "web_search") {
    const summary = extractText(item) || summarizeItem(item);
    return [{
      kind: "tool",
      title: formatEventTitle(type, "Web search"),
      summary: compactOneLine(summary),
      detail: summary
    }];
  }

  if (type.startsWith("item.")) {
    return [{
      kind: "activity",
      title: formatEventTitle(type, item.type || "Item"),
      detail: extractText(item) || summarizeItem(item)
    }];
  }

  return [{ kind: "activity", title: type, detail: compactJson(event) }];
}

function extractText(value) {
  if (!value || typeof value !== "object") {
    return typeof value === "string" ? value : "";
  }

  for (const key of ["text", "message", "content", "output", "result", "summary"]) {
    const candidate = value[key];
    if (typeof candidate === "string") {
      return candidate;
    }
    if (Array.isArray(candidate)) {
      const joined = candidate
        .map((entry) => typeof entry === "string" ? entry : extractText(entry))
        .filter(Boolean)
        .join("\n");
      if (joined) {
        return joined;
      }
    }
  }

  return "";
}

function isToolItem(item) {
  return [
    "tool_call",
    "mcp_tool_call",
    "function_call",
    "local_shell",
    "patch",
    "file_change"
  ].includes(item.type);
}

function formatToolTitle(item) {
  return item.name || item.tool_name || item.server_name || item.type || "Tool";
}

function formatEventTitle(eventType, label) {
  if (eventType === "item.started") {
    return `${label} started`;
  }
  if (eventType === "item.completed") {
    return `${label} completed`;
  }
  if (eventType === "item.failed") {
    return `${label} failed`;
  }
  return label;
}

function formatCommandTitle(eventType, item) {
  const command = formatCommand(item.command);
  const label = command ? `$ ${compactOneLine(command)}` : "Command";
  return formatEventTitle(eventType, label);
}

function formatCommandSummary(item) {
  const parts = [];
  const command = formatCommand(item.command);
  if (command) {
    parts.push(command);
  }
  if (item.exit_code !== undefined) {
    parts.push(`exit code: ${item.exit_code}`);
  }
  const text = extractText(item);
  if (text) {
    parts.push(compactOneLine(text));
  }
  return compactOneLine(parts.join(" | "));
}

function formatCommandExecution(item) {
  const parts = [];
  const command = formatCommand(item.command);
  if (command) {
    parts.push(`$ ${command}`);
  }
  if (item.exit_code !== undefined) {
    parts.push(`exit code: ${item.exit_code}`);
  }
  const text = extractText(item);
  if (text) {
    parts.push(text);
  }
  return parts.join("\n\n") || summarizeItem(item);
}

function formatCommand(command) {
  if (Array.isArray(command)) {
    return command.map((part) => String(part)).join(" ");
  }
  if (command === undefined || command === null) {
    return "";
  }
  return String(command);
}

function compactOneLine(text) {
  return String(text || "")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, 180);
}

function formatUsage(usage) {
  if (!usage || typeof usage !== "object") {
    return "";
  }

  const parts = [];
  for (const [key, value] of Object.entries(usage)) {
    if (typeof value === "number") {
      parts.push(`${key}: ${value}`);
    }
  }
  return parts.join(", ");
}

function summarizeItem(item) {
  const summary = {};
  for (const key of ["type", "status", "name", "tool_name", "server_name", "command", "exit_code", "path"]) {
    if (item[key] !== undefined) {
      summary[key] = item[key];
    }
  }
  return Object.keys(summary).length > 0 ? compactJson(summary) : compactJson(item);
}

function compactJson(value) {
  try {
    return JSON.stringify(value, null, 2);
  } catch {
    return String(value);
  }
}

module.exports = {
  codexJsonEventToUpdates
};

},
"src/agents/codex/CodexAgent.js": function(module, exports, __require) {
const { Notice } = require("obsidian");
const { spawn } = require("child_process");
const fs = require("fs/promises");
const os = require("os");
const path = require("path");

const { parseArgsTemplate, withJsonOutput, withOutputLastMessage } = __require("src/cli/args.js");
const { buildCliPath } = __require("src/cli/env.js");
const { escapeAppleScriptString, shellQuote } = __require("src/cli/shell.js");
const { applyModeArgs } = __require("src/modes.js");
const { buildPromptWithMetadata } = __require("src/prompt.js");
const { DEFAULT_SETTINGS } = __require("src/settings.js");
const { codexJsonEventToUpdates } = __require("src/agents/codex/jsonEvents.js");

class CodexAgent {
  constructor(plugin) {
    this.plugin = plugin;
    this.id = "codex";
    this.label = "Codex";
  }

  async run(prompt, onUpdate, conversation) {
    const settings = this.plugin.settings;
    const cwd = this.getWorkingDirectory();
    const promptResult = await buildPromptWithMetadata(this.plugin.app, settings, prompt, conversation);
    const finalPrompt = promptResult.prompt;
    if (promptResult.context.compressed) {
      onUpdate({
        kind: "notice",
        title: "Context compressed",
        summary: `Compressed ${formatNumber(promptResult.context.originalChars)} chars into ${formatNumber(promptResult.context.promptChars)} / ${formatNumber(promptResult.context.limitChars)} chars.`
      });
    }
    const outputPath = path.join(
      os.tmpdir(),
      `obsidian-agent-dock-${Date.now()}-${Math.random().toString(16).slice(2)}.txt`
    );
    const args = withJsonOutput(
      withOutputLastMessage(
        applyModeArgs(
          parseArgsTemplate(settings.args, finalPrompt, DEFAULT_SETTINGS.args),
          settings.mode,
          DEFAULT_SETTINGS.mode
        ),
        outputPath
      )
    );

    return new Promise((resolve, reject) => {
      let finalOutput = "";
      let errorOutput = "";
      let stdoutBuffer = "";

      const child = spawn(settings.codexPath, args, {
        cwd,
        shell: false,
        env: Object.assign({}, process.env, {
          PATH: buildCliPath(process.env.PATH),
          TERM: "dumb"
        }),
        stdio: ["ignore", "pipe", "pipe"]
      });

      const handleJsonLine = (line) => {
        if (!line.trim()) {
          return;
        }

        try {
          const event = JSON.parse(line);
          const updates = codexJsonEventToUpdates(event);
          for (const update of updates) {
            if (update.kind === "content") {
              finalOutput += update.text;
            }
            onUpdate(update);
          }
        } catch {
          onUpdate({ kind: "activity", title: "Raw output", detail: line });
        }
      };

      child.stdout.on("data", (data) => {
        stdoutBuffer += data.toString();
        const lines = stdoutBuffer.split(/\r?\n/);
        stdoutBuffer = lines.pop() || "";
        for (const line of lines) {
          handleJsonLine(line);
        }
      });

      child.stderr.on("data", (data) => {
        errorOutput += data.toString();
        const text = data.toString().trim();
        if (text) {
          onUpdate({ kind: "activity", title: "Codex", detail: text });
        }
      });

      child.on("error", (error) => reject(error));
      child.on("close", async (code) => {
        if (stdoutBuffer.trim()) {
          handleJsonLine(stdoutBuffer);
        }

        const fileOutput = await readOutputFile(outputPath);
        if (!finalOutput.trim() && fileOutput) {
          finalOutput = fileOutput;
          onUpdate({ kind: "content", text: fileOutput });
        }

        if (code === 0) {
          resolve(finalOutput.trim());
          return;
        }

        const details = [errorOutput.trim(), fileOutput.trim()]
          .filter(Boolean)
          .join("\n\n");
        reject(new Error(details || `Codex exited with code ${code}`));
      });
    });
  }

  async openInteractive() {
    if (process.platform !== "darwin") {
      new Notice("Interactive Codex launch is currently implemented for macOS Terminal.");
      return;
    }

    const settings = this.plugin.settings;
    const cwd = this.getWorkingDirectory();
    const command = [
      `cd ${shellQuote(cwd)}`,
      `${shellQuote(settings.codexPath)} ${settings.interactiveArgs || ""}`.trim()
    ].join(" && ");
    const script = [
      "tell application \"Terminal\"",
      "activate",
      `do script "${escapeAppleScriptString(command)}"`,
      "end tell"
    ].join("\n");

    await new Promise((resolve, reject) => {
      const child = spawn("osascript", ["-e", script], {
        env: Object.assign({}, process.env, {
          PATH: buildCliPath(process.env.PATH)
        }),
        stdio: ["ignore", "pipe", "pipe"]
      });

      let errorOutput = "";
      child.stderr.on("data", (data) => {
        errorOutput += data.toString();
      });
      child.on("error", (error) => reject(error));
      child.on("close", (code) => {
        if (code === 0) {
          resolve();
          return;
        }

        reject(new Error(errorOutput.trim() || `Terminal exited with code ${code}`));
      });
    });
  }

  getWorkingDirectory() {
    return this.plugin.settings.workingDirectory || this.plugin.app.vault.adapter.basePath;
  }
}

async function readOutputFile(outputPath) {
  try {
    const content = await fs.readFile(outputPath, "utf8");
    await fs.unlink(outputPath).catch(() => {});
    return content;
  } catch {
    return "";
  }
}

function formatNumber(value) {
  return new Intl.NumberFormat().format(value);
}

module.exports = {
  CodexAgent
};

},
"src/agents/AgentRegistry.js": function(module, exports, __require) {
const { CodexAgent } = __require("src/agents/codex/CodexAgent.js");

function createAgent(plugin) {
  switch (plugin.settings.agentId) {
    case "codex":
    default:
      return new CodexAgent(plugin);
  }
}

const AGENT_OPTIONS = {
  codex: {
    label: "Codex",
    description: "OpenAI Codex CLI"
  }
};

module.exports = {
  AGENT_OPTIONS,
  createAgent
};

},
"src/constants.js": function(module, exports, __require) {
const VIEW_TYPE_AGENT_DOCK = "codex-dock-view";

module.exports = {
  VIEW_TYPE_AGENT_DOCK
};

},
"src/settingsTab.js": function(module, exports, __require) {
const { PluginSettingTab, Setting } = require("obsidian");

const { AGENT_OPTIONS } = __require("src/agents/AgentRegistry.js");
const { DEFAULT_SETTINGS } = __require("src/settings.js");

class AgentDockSettingTab extends PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }

  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Agent Dock" });

    new Setting(containerEl)
      .setName("Agent provider")
      .setDesc("Adapter used by the dock. More providers can be added without changing the UI.")
      .addDropdown((dropdown) => {
        for (const [id, option] of Object.entries(AGENT_OPTIONS)) {
          dropdown.addOption(id, option.label);
        }
        dropdown
          .setValue(this.plugin.settings.agentId)
          .onChange(async (value) => {
            this.plugin.settings.agentId = value;
            this.plugin.refreshAgent();
            await this.plugin.saveSettings();
          });
      });

    new Setting(containerEl)
      .setName("Codex executable path")
      .setDesc("Full path to the Codex CLI executable. GUI apps often cannot find shell commands by name.")
      .addText((text) => text
        .setPlaceholder("/opt/homebrew/bin/codex")
        .setValue(this.plugin.settings.codexPath)
        .onChange(async (value) => {
          this.plugin.settings.codexPath = value.trim() || DEFAULT_SETTINGS.codexPath;
          await this.plugin.saveSettings();
        }));

    new Setting(containerEl)
      .setName("Arguments")
      .setDesc("Use {{prompt}} where the prompt should be inserted.")
      .addText((text) => text
        .setPlaceholder("exec {{prompt}}")
        .setValue(this.plugin.settings.args)
        .onChange(async (value) => {
          this.plugin.settings.args = value.trim() || DEFAULT_SETTINGS.args;
          await this.plugin.saveSettings();
        }));

    new Setting(containerEl)
      .setName("Interactive arguments")
      .setDesc("Optional arguments used when opening the full agent TUI in Terminal.")
      .addText((text) => text
        .setPlaceholder("--sandbox workspace-write")
        .setValue(this.plugin.settings.interactiveArgs)
        .onChange(async (value) => {
          this.plugin.settings.interactiveArgs = value.trim();
          await this.plugin.saveSettings();
        }));

    new Setting(containerEl)
      .setName("Working directory")
      .setDesc("Defaults to the vault folder.")
      .addText((text) => text
        .setPlaceholder("/path/to/project")
        .setValue(this.plugin.settings.workingDirectory)
        .onChange(async (value) => {
          this.plugin.settings.workingDirectory = value.trim();
          await this.plugin.saveSettings();
        }));

    new Setting(containerEl)
      .setName("Include active note")
      .setDesc("Send the current note content along with your request.")
      .addToggle((toggle) => toggle
        .setValue(this.plugin.settings.includeActiveNote)
        .onChange(async (value) => {
          this.plugin.settings.includeActiveNote = value;
          await this.plugin.saveSettings();
        }));

    new Setting(containerEl)
      .setName("Debug activity")
      .setDesc("Show streamed reasoning summaries, tool calls, command output, stderr, and raw events under each response.")
      .addToggle((toggle) => toggle
        .setValue(this.plugin.settings.debugActivity)
        .onChange(async (value) => {
          this.plugin.settings.debugActivity = value;
          await this.plugin.saveSettings();
        }));

    new Setting(containerEl)
      .setName("Active note character limit")
      .setDesc("Prevents very large notes from overwhelming the command.")
      .addText((text) => text
        .setPlaceholder(String(DEFAULT_SETTINGS.activeNoteMaxChars))
        .setValue(String(this.plugin.settings.activeNoteMaxChars))
        .onChange(async (value) => {
          const parsed = Number.parseInt(value, 10);
          this.plugin.settings.activeNoteMaxChars = Number.isFinite(parsed) && parsed > 0
            ? parsed
            : DEFAULT_SETTINGS.activeNoteMaxChars;
          await this.plugin.saveSettings();
        }));

    new Setting(containerEl)
      .setName("Context character limit")
      .setDesc("Maximum prompt size before older conversation history is compressed. Default is 258k characters.")
      .addText((text) => text
        .setPlaceholder(String(DEFAULT_SETTINGS.contextLimitChars))
        .setValue(String(this.plugin.settings.contextLimitChars))
        .onChange(async (value) => {
          const parsed = Number.parseInt(value, 10);
          this.plugin.settings.contextLimitChars = Number.isFinite(parsed) && parsed > 0
            ? parsed
            : DEFAULT_SETTINGS.contextLimitChars;
          await this.plugin.saveSettings();
        }));
  }
}

module.exports = {
  AgentDockSettingTab
};

},
"src/view/AgentDockView.js": function(module, exports, __require) {
const { ItemView, MarkdownRenderer, Notice } = require("obsidian");

const { VIEW_TYPE_AGENT_DOCK } = __require("src/constants.js");
const { MODE_OPTIONS, getModeDescription } = __require("src/modes.js");
const { DEFAULT_SETTINGS } = __require("src/settings.js");

class AgentDockView extends ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
    this.sessions = [];
    this.activeSessionId = "";
    this.isRunning = false;
  }

  getViewType() {
    return VIEW_TYPE_AGENT_DOCK;
  }

  getDisplayText() {
    return "Agent Dock";
  }

  getIcon() {
    return "bot";
  }

  async onOpen() {
    this.ensureActiveSession();
    this.render();
  }

  render() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.addClass("codex-dock");

    const header = containerEl.createDiv({ cls: "codex-dock__header" });
    header.createDiv({ cls: "codex-dock__title", text: this.plugin.agent.label });

    const actions = header.createDiv({ cls: "codex-dock__actions" });
    const terminalButton = actions.createEl("button", {
      cls: "codex-dock__icon-button",
      attr: { "aria-label": "Open interactive agent in Terminal", title: "Open interactive agent in Terminal" }
    });
    terminalButton.setText("Terminal");
    terminalButton.addEventListener("click", async () => {
      try {
        await this.plugin.openInteractiveAgent();
      } catch (error) {
        new Notice(`Could not open Terminal: ${error.message}`);
      }
    });

    const clearButton = actions.createEl("button", {
      cls: "codex-dock__icon-button",
      attr: { "aria-label": "Clear conversation", title: "Clear conversation" }
    });
    clearButton.setText("Clear");
    clearButton.addEventListener("click", () => {
      if (this.isRunning) {
        new Notice(`${this.plugin.agent.label} is still working.`);
        return;
      }
      const session = this.getActiveSession();
      if (session) {
        session.messages = [];
        this.renderMessages();
      }
    });

    const sessionBar = containerEl.createDiv({ cls: "codex-dock__session-bar" });
    this.sessionSelectEl = sessionBar.createEl("select", {
      cls: "codex-dock__session-select",
      attr: { "aria-label": "Conversation" }
    });
    this.sessionSelectEl.addEventListener("change", () => {
      this.activeSessionId = this.sessionSelectEl.value;
      this.renderMessages();
    });

    const newSessionButton = sessionBar.createEl("button", {
      cls: "codex-dock__icon-button",
      attr: { type: "button", "aria-label": "New conversation", title: "New conversation" }
    });
    newSessionButton.setText("New");
    newSessionButton.addEventListener("click", () => {
      this.createSession();
      this.render();
    });
    this.updateSessionSelectOptions();

    this.messageList = containerEl.createDiv({ cls: "codex-dock__messages" });
    this.renderMessages();

    const composer = containerEl.createDiv({ cls: "codex-dock__composer" });
    this.inputEl = composer.createEl("textarea", {
      cls: "codex-dock__input",
      attr: {
        rows: "4",
        placeholder: "Ask the agent about this vault or the active note..."
      }
    });

    this.inputEl.addEventListener("keydown", (event) => {
      if (event.key === "Enter" && (event.metaKey || event.ctrlKey)) {
        event.preventDefault();
        this.submit();
      }
    });
    this.inputEl.addEventListener("input", () => this.updateContextStatus());

    const modeRow = composer.createDiv({ cls: "codex-dock__mode-row" });
    modeRow.createEl("label", {
      cls: "codex-dock__mode-label",
      text: "Mode",
      attr: { for: "codex-dock-mode" }
    });
    const modeSelect = modeRow.createEl("select", {
      cls: "codex-dock__mode-select",
      attr: { id: "codex-dock-mode" }
    });

    for (const [value, option] of Object.entries(MODE_OPTIONS)) {
      modeSelect.createEl("option", {
        text: option.label,
        value
      });
    }

    modeSelect.value = this.plugin.settings.mode;
    const modeHint = composer.createDiv({
      cls: "codex-dock__mode-hint",
      text: getModeDescription(this.plugin.settings.mode, DEFAULT_SETTINGS.mode)
    });

    modeSelect.addEventListener("change", async () => {
      this.plugin.settings.mode = modeSelect.value;
      modeHint.setText(getModeDescription(this.plugin.settings.mode, DEFAULT_SETTINGS.mode));
      await this.plugin.saveSettings();
      this.updateContextStatus();
    });

    this.contextStatusEl = composer.createDiv({ cls: "codex-dock__context-status" });
    this.updateContextStatus();

    const sendButton = composer.createEl("button", { cls: "mod-cta codex-dock__send" });
    sendButton.setText("Send");
    sendButton.addEventListener("click", () => this.submit());
  }

  renderMessages() {
    this.messageList.empty();
    const session = this.ensureActiveSession();
    const messages = session.messages;

    if (messages.length === 0) {
      const empty = this.messageList.createDiv({ cls: "codex-dock__empty" });
      empty.createDiv({ text: "Open a side conversation with an agent." });
      empty.createDiv({ text: "The active note can be included automatically." });
      this.updateContextStatus();
      return;
    }

    for (const message of messages) {
      const item = this.messageList.createDiv({
        cls: `codex-dock__message codex-dock__message--${message.role}`
      });
      item.createDiv({
        cls: "codex-dock__role",
        text: message.role === "user" ? "You" : this.plugin.agent.label
      });
      if (message.timeline && message.timeline.length > 0) {
        const timeline = item.createDiv({ cls: "codex-dock__timeline" });
        this.renderTimeline(timeline, message);
      } else if (message.content) {
        this.renderMarkdownContent(item, message.content);
      }
      if (message.isLoading) {
        const loading = item.createDiv({ cls: "codex-dock__loading" });
        const dots = loading.createSpan({ cls: "codex-dock__loading-dots", attr: { "aria-hidden": "true" } });
        dots.createSpan();
        dots.createSpan();
        dots.createSpan();
      }
    }

    this.messageList.scrollTop = this.messageList.scrollHeight;
    this.updateContextStatus();
  }

  async submit() {
    if (this.isRunning) {
      new Notice(`${this.plugin.agent.label} is still working.`);
      return;
    }

    const prompt = this.inputEl.value.trim();
    if (!prompt) {
      return;
    }

    const session = this.ensureActiveSession();
    this.maybeNameSession(session, prompt);
    this.updateSessionSelectOptions();
    this.inputEl.value = "";
    session.messages.push({
      role: "user",
      content: prompt,
      timeline: [{ kind: "message", text: prompt }]
    });
    const assistantMessage = { role: "assistant", content: "", timeline: [], isLoading: true };
    session.messages.push(assistantMessage);
    this.isRunning = true;
    this.renderMessages();

    try {
      const conversation = session.messages.slice(0, -1);
      await this.plugin.runAgent(prompt, (update) => {
        if (assistantMessage.isComplete) {
          return;
        }

        if (update.kind === "content") {
          assistantMessage.content += update.text;
          appendTimelineContent(assistantMessage, update.text);
        } else {
          assistantMessage.timeline.push(update);
        }
        this.renderMessages();
      }, conversation);

      assistantMessage.isLoading = false;
      assistantMessage.isComplete = true;
      if (!assistantMessage.content.trim()) {
        const emptyText = `(${this.plugin.agent.label} finished without text output.)`;
        assistantMessage.content = emptyText;
        appendTimelineContent(assistantMessage, emptyText);
      }
      this.renderMessages();
    } catch (error) {
      assistantMessage.isLoading = false;
      assistantMessage.isComplete = true;
      const errorText = [
        `${this.plugin.agent.label} could not run.`,
        "",
        error.message,
        "",
        "Check the executable path in plugin settings and make sure the CLI is installed and allowed by macOS."
      ].join("\n");
      assistantMessage.content = errorText;
      appendTimelineContent(assistantMessage, errorText);
      this.renderMessages();
      new Notice(`${this.plugin.agent.label} command failed.`);
    } finally {
      this.isRunning = false;
    }
  }

  renderTimeline(containerEl, message) {
    if (message.role !== "assistant") {
      for (const entry of message.timeline) {
        this.renderTimelineEntry(containerEl, entry);
      }
      return;
    }

    if (message.isComplete) {
      this.renderCompletedTimeline(containerEl, message.timeline);
      return;
    }

    for (const group of groupLiveTimeline(message.timeline, this.plugin.settings.debugActivity)) {
      if (group.type === "eventGroup") {
        this.renderEventGroup(containerEl, group.entries, group.label, false);
      } else {
        this.renderTimelineEntry(containerEl, group.entry);
      }
    }
  }

  renderCompletedTimeline(containerEl, timeline) {
    const finalContentIndex = findLastContentIndex(timeline);

    if (finalContentIndex === -1) {
      this.renderProcessedGroup(containerEl, timeline.filter((entry) => this.shouldShowEvent(entry)));
      return;
    }

    const processedEntries = timeline.filter((entry, index) => {
      if (index === finalContentIndex) {
        return false;
      }
      return entry.kind === "content" || this.shouldShowEvent(entry);
    });

    if (processedEntries.length > 0) {
      this.renderProcessedGroup(containerEl, processedEntries);
    }

    this.renderTimelineEntry(containerEl, timeline[finalContentIndex]);
  }

  renderProcessedGroup(containerEl, entries) {
    if (entries.length === 0) {
      return;
    }

    const details = containerEl.createEl("details", {
      cls: "codex-dock__event-group codex-dock__event-group--processed"
    });
    details.open = false;
    details.createEl("summary", {
      cls: "codex-dock__event-group-summary",
      text: `已处理 ${entries.length} 项`
    });

    const body = details.createDiv({ cls: "codex-dock__event-group-body" });
    for (const group of groupProcessedEntries(entries)) {
      if (group.type === "eventGroup") {
        this.renderEventGroup(body, group.entries, getEventGroupLabel(group.entries), false);
      } else {
        this.renderTimelineEntry(body, group.entry);
      }
    }
  }

  renderEventGroup(containerEl, entries, label, open) {
    const details = containerEl.createEl("details", {
      cls: "codex-dock__event-group"
    });
    details.open = open;
    details.createEl("summary", {
      cls: "codex-dock__event-group-summary",
      text: label
    });

    const body = details.createDiv({ cls: "codex-dock__event-group-body" });
    for (const entry of entries) {
      this.renderTimelineEntry(body, entry, { forceDetail: this.plugin.settings.debugActivity });
    }
  }

  renderTimelineEntry(containerEl, entry) {
    if (entry.kind === "message" || entry.kind === "content") {
      this.renderMarkdownContent(containerEl, entry.text);
      return;
    }

    if (!this.shouldShowEvent(entry)) {
      return;
    }

    const eventEl = containerEl.createDiv({ cls: `codex-dock__event codex-dock__event--${entry.kind || "activity"}` });
    eventEl.createDiv({ cls: "codex-dock__event-title", text: entry.title || "Event" });
    if (entry.summary && !this.plugin.settings.debugActivity) {
      eventEl.createDiv({ cls: "codex-dock__event-summary", text: entry.summary });
    }
    if (entry.detail && this.plugin.settings.debugActivity) {
      eventEl.createEl("pre", { cls: "codex-dock__event-detail", text: entry.detail });
    }
  }

  renderMarkdownContent(containerEl, text) {
    const contentEl = containerEl.createDiv({ cls: "codex-dock__content markdown-rendered" });
    const copyButton = contentEl.createEl("button", {
      cls: "codex-dock__copy-button",
      text: "Copy",
      attr: {
        type: "button",
        "aria-label": "Copy message text",
        title: "Copy message text"
      }
    });
    copyButton.addEventListener("click", async (event) => {
      event.preventDefault();
      event.stopPropagation();
      await copyText(text || "");
      copyButton.setText("Copied");
      window.setTimeout(() => copyButton.setText("Copy"), 1200);
    });

    const markdownEl = contentEl.createDiv({ cls: "codex-dock__content-body" });
    const sourcePath = this.app.workspace.getActiveFile()?.path || "";
    MarkdownRenderer.render(this.app, text || "", markdownEl, sourcePath, this).catch(() => {
      markdownEl.setText(text || "");
    });
  }

  shouldShowEvent(entry) {
    if (this.plugin.settings.debugActivity) {
      return true;
    }

    return ["reasoning", "tool", "error", "notice"].includes(entry.kind);
  }

  updateContextStatus() {
    if (!this.contextStatusEl) {
      return;
    }

    const session = this.getActiveSession();
    const limit = Number(this.plugin.settings.contextLimitChars) || DEFAULT_SETTINGS.contextLimitChars;
    const used = estimateContextChars(session?.messages || [], this.inputEl?.value || "", this.plugin.settings);
    const percent = Math.min(999, Math.round((used / limit) * 100));
    this.contextStatusEl.toggleClass("is-warning", percent >= 80);
    this.contextStatusEl.toggleClass("is-over", percent >= 100);
    this.contextStatusEl.setText(`Context ${percent}% · ${formatCompactNumber(used)} / ${formatCompactNumber(limit)} chars`);
  }

  ensureActiveSession() {
    if (this.sessions.length === 0) {
      return this.createSession();
    }

    const existing = this.getActiveSession();
    if (existing) {
      return existing;
    }

    this.activeSessionId = this.sessions[0].id;
    return this.sessions[0];
  }

  createSession() {
    const session = {
      id: `session-${Date.now()}-${Math.random().toString(16).slice(2)}`,
      title: `Chat ${this.sessions.length + 1}`,
      isUntitled: true,
      messages: []
    };
    this.sessions.push(session);
    this.activeSessionId = session.id;
    return session;
  }

  getActiveSession() {
    return this.sessions.find((session) => session.id === this.activeSessionId) || null;
  }

  maybeNameSession(session, prompt) {
    if (!session.isUntitled) {
      return;
    }

    const compact = prompt.replace(/\s+/g, " ").trim();
    session.title = compact.length > 28 ? `${compact.slice(0, 28)}...` : compact || session.title;
    session.isUntitled = false;
  }

  updateSessionSelectOptions() {
    if (!this.sessionSelectEl) {
      return;
    }

    this.sessionSelectEl.empty();
    for (const session of this.sessions) {
      this.sessionSelectEl.createEl("option", {
        text: session.title,
        value: session.id
      });
    }
    this.sessionSelectEl.value = this.activeSessionId;
  }
}

function estimateContextChars(messages, draft, settings) {
  const transcriptChars = messages.reduce((total, message) => {
    return total + String(message.content || "").length + 16;
  }, 0);
  const draftChars = String(draft || "").length + 16;
  const noteChars = settings.includeActiveNote
    ? (Number(settings.activeNoteMaxChars) || DEFAULT_SETTINGS.activeNoteMaxChars)
    : 0;
  return transcriptChars + draftChars + noteChars;
}

function formatCompactNumber(value) {
  if (value >= 1000) {
    return `${Math.round(value / 1000)}k`;
  }
  return String(value);
}

async function copyText(text) {
  if (navigator.clipboard?.writeText) {
    await navigator.clipboard.writeText(text);
    return;
  }

  const textarea = document.createElement("textarea");
  textarea.value = text;
  textarea.style.position = "fixed";
  textarea.style.opacity = "0";
  document.body.appendChild(textarea);
  textarea.select();
  document.execCommand("copy");
  textarea.remove();
}

function appendTimelineContent(message, text) {
  const lastEntry = message.timeline[message.timeline.length - 1];
  if (lastEntry && lastEntry.kind === "content") {
    lastEntry.text += text;
    return;
  }

  message.timeline.push({ kind: "content", text });
}

function findLastContentIndex(timeline) {
  for (let index = timeline.length - 1; index >= 0; index -= 1) {
    if (timeline[index].kind === "content") {
      return index;
    }
  }
  return -1;
}

function groupLiveTimeline(timeline, debugActivity) {
  const groups = [];
  let pendingEvents = [];

  const flushPendingEvents = () => {
    if (pendingEvents.length === 0) {
      return;
    }

    groups.push({
      type: "eventGroup",
      label: getEventGroupLabel(pendingEvents),
      entries: pendingEvents
    });
    pendingEvents = [];
  };

  for (const entry of timeline) {
    if (entry.kind === "content") {
      flushPendingEvents();
      groups.push({ type: "entry", entry });
      continue;
    }

    if (debugActivity || ["reasoning", "tool", "error"].includes(entry.kind)) {
      const previous = pendingEvents[pendingEvents.length - 1];
      if (previous && previous.kind !== entry.kind) {
        flushPendingEvents();
      }
      pendingEvents.push(entry);
    }
  }

  flushPendingEvents();
  return groups;
}

function groupProcessedEntries(entries) {
  const groups = [];
  let pending = [];

  const flush = () => {
    if (pending.length === 0) {
      return;
    }

    groups.push({ type: "eventGroup", entries: pending });
    pending = [];
  };

  for (const entry of entries) {
    if (entry.kind === "content") {
      flush();
      groups.push({ type: "entry", entry });
      continue;
    }

    const previous = pending[pending.length - 1];
    if (previous && previous.kind !== entry.kind) {
      flush();
    }
    pending.push(entry);
  }

  flush();
  return groups;
}

function getEventGroupLabel(entries) {
  const hasError = entries.some((entry) => entry.kind === "error");
  if (hasError) {
    return `需要关注 ${entries.length} 项`;
  }

  const hasTool = entries.some((entry) => entry.kind === "tool");
  const hasReasoning = entries.some((entry) => entry.kind === "reasoning");
  const hasNotice = entries.some((entry) => entry.kind === "notice");
  const label = hasTool ? "工具调用" : hasReasoning ? "思考" : hasNotice ? "提示" : "活动";
  return `${label} ${entries.length} 项`;
}

module.exports = {
  AgentDockView
};

},
"src/plugin.js": function(module, exports, __require) {
const { Plugin } = require("obsidian");

const { createAgent } = __require("src/agents/AgentRegistry.js");
const { VIEW_TYPE_AGENT_DOCK } = __require("src/constants.js");
const { normalizeSettings } = __require("src/settings.js");
const { AgentDockSettingTab } = __require("src/settingsTab.js");
const { AgentDockView } = __require("src/view/AgentDockView.js");

module.exports = class AgentDockPlugin extends Plugin {
  async onload() {
    this.settings = normalizeSettings(await this.loadData());
    this.refreshAgent();

    this.registerView(
      VIEW_TYPE_AGENT_DOCK,
      (leaf) => new AgentDockView(leaf, this)
    );

    this.addRibbonIcon("bot", "Open Agent Dock", () => this.activateView());
    this.addCommand({
      id: "open-agent-dock",
      name: "Open Agent Dock",
      callback: () => this.activateView()
    });
    this.addCommand({
      id: "open-interactive-agent",
      name: "Open interactive agent in Terminal",
      callback: () => this.openInteractiveAgent()
    });

    this.addSettingTab(new AgentDockSettingTab(this.app, this));
  }

  async onunload() {
    this.app.workspace.detachLeavesOfType(VIEW_TYPE_AGENT_DOCK);
  }

  refreshAgent() {
    this.agent = createAgent(this);
  }

  async saveSettings() {
    await this.saveData(this.settings);
  }

  async activateView() {
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_AGENT_DOCK);
    let leaf = leaves[0];

    if (!leaf) {
      leaf = this.app.workspace.getRightLeaf(false);
      await leaf.setViewState({ type: VIEW_TYPE_AGENT_DOCK, active: true });
    }

    this.app.workspace.revealLeaf(leaf);
  }

  async runAgent(prompt, onUpdate, conversation) {
    return this.agent.run(prompt, onUpdate, conversation);
  }

  async openInteractiveAgent() {
    return this.agent.openInteractive();
  }
};

}
};

const __cache = {};
function __require(id) {
  if (!__modules[id]) {
    return require(id);
  }

  if (__cache[id]) {
    return __cache[id].exports;
  }

  const module = { exports: {} };
  __cache[id] = module;
  __modules[id](module, module.exports, __require);
  return module.exports;
}

module.exports = __require("src/plugin.js");
