// Generated by scripts/build-main.js. Edit src/ files instead.
const __modules = {
"src/cli/args.js": function(module, exports, __require) {
function parseArgsTemplate(template, prompt, defaultArgs) {
  const tokens = [];
  const source = template || defaultArgs;
  let current = "";
  let quote = null;

  for (let index = 0; index < source.length; index += 1) {
    const char = source[index];

    if ((char === "\"" || char === "'") && !quote) {
      quote = char;
      continue;
    }

    if (char === quote) {
      quote = null;
      continue;
    }

    if (/\s/.test(char) && !quote) {
      if (current) {
        tokens.push(current);
        current = "";
      }
      continue;
    }

    current += char;
  }

  if (current) {
    tokens.push(current);
  }

  return tokens.map((token) => token.replace(/\{\{prompt\}\}/g, prompt));
}

function withOutputLastMessage(args, outputPath) {
  if (!args.includes("-o") && !args.includes("--output-last-message")) {
    const execIndex = args.indexOf("exec");
    if (execIndex >= 0) {
      return [
        ...args.slice(0, execIndex + 1),
        "--output-last-message",
        outputPath,
        ...args.slice(execIndex + 1)
      ];
    }
  }

  return args;
}

function withJsonOutput(args) {
  if (args.includes("--json")) {
    return args;
  }

  const execIndex = args.indexOf("exec");
  if (execIndex >= 0) {
    return [
      ...args.slice(0, execIndex + 1),
      "--json",
      ...args.slice(execIndex + 1)
    ];
  }

  return args;
}

module.exports = {
  parseArgsTemplate,
  withJsonOutput,
  withOutputLastMessage
};

},
"src/cli/env.js": function(module, exports, __require) {
function buildCliPath(existingPath) {
  const pathParts = [
    "/opt/homebrew/bin",
    "/usr/local/bin",
    "/usr/bin",
    "/bin",
    "/usr/sbin",
    "/sbin"
  ];

  for (const part of (existingPath || "").split(":")) {
    if (part && !pathParts.includes(part)) {
      pathParts.push(part);
    }
  }

  return pathParts.join(":");
}

module.exports = {
  buildCliPath
};

},
"src/cli/shell.js": function(module, exports, __require) {
function shellQuote(value) {
  return `'${String(value).replace(/'/g, "'\\''")}'`;
}

function escapeAppleScriptString(value) {
  return String(value)
    .replace(/\\/g, "\\\\")
    .replace(/"/g, "\\\"");
}

module.exports = {
  escapeAppleScriptString,
  shellQuote
};

},
"src/modes.js": function(module, exports, __require) {
const MODE_OPTIONS = {
  readOnly: {
    label: "Read only",
    description: "Inspect vault files but do not write.",
    args: ["--sandbox", "read-only"]
  },
  workspaceWrite: {
    label: "Workspace write",
    description: "Allow edits inside the vault or working directory.",
    args: ["--sandbox", "workspace-write", "--skip-git-repo-check"]
  },
  fullAccess: {
    label: "Full access",
    description: "Allow broad local access. Use carefully.",
    args: ["--sandbox", "danger-full-access", "--skip-git-repo-check"]
  }
};

function applyModeArgs(args, mode, defaultMode) {
  const modeConfig = MODE_OPTIONS[mode] || MODE_OPTIONS[defaultMode];
  const execIndex = args.indexOf("exec");
  if (execIndex < 0) {
    return args;
  }

  const additions = [];
  const hasSandbox = args.includes("--sandbox") || args.includes("-s");
  const hasDangerBypass = args.includes("--dangerously-bypass-approvals-and-sandbox");
  const hasSkipGitRepoCheck = args.includes("--skip-git-repo-check");

  for (let index = 0; index < modeConfig.args.length; index += 1) {
    const flag = modeConfig.args[index];
    const value = modeConfig.args[index + 1];

    if (flag === "--sandbox") {
      if (!hasSandbox && !hasDangerBypass) {
        additions.push(flag, value);
      }
      index += 1;
      continue;
    }

    if (flag === "--skip-git-repo-check" && !hasSkipGitRepoCheck) {
      additions.push(flag);
    }
  }

  return [
    ...args.slice(0, execIndex + 1),
    ...additions,
    ...args.slice(execIndex + 1)
  ];
}

function getModeDescription(mode, defaultMode) {
  return (MODE_OPTIONS[mode] || MODE_OPTIONS[defaultMode]).description;
}

module.exports = {
  MODE_OPTIONS,
  applyModeArgs,
  getModeDescription
};

},
"src/prompt.js": function(module, exports, __require) {
async function buildPrompt(app, settings, prompt, conversation) {
  const result = await buildPromptWithMetadata(app, settings, prompt, conversation);
  return result.prompt;
}

async function buildPromptWithMetadata(app, settings, prompt, conversation) {
  const promptParts = [];
  const contextLimit = Number(settings.contextLimitChars) || 258000;
  const referencedPrompt = await buildReferencedPathsPrompt(app, prompt, contextLimit);

  if (!settings.includeActiveNote) {
    const conversationBudget = Math.max(1000, contextLimit - referencedPrompt.length);
    promptParts.push(
      referencedPrompt,
      formatConversationPrompt(prompt, conversation, conversationBudget)
    );
    return buildPromptResult(promptParts.filter(Boolean).join("\n"), contextLimit);
  }

  const file = app.workspace.getActiveFile();
  if (!file) {
    const conversationBudget = Math.max(1000, contextLimit - referencedPrompt.length);
    promptParts.push(
      referencedPrompt,
      formatConversationPrompt(prompt, conversation, conversationBudget)
    );
    return buildPromptResult(promptParts.filter(Boolean).join("\n"), contextLimit);
  }

  const note = await app.vault.cachedRead(file);
  const maxChars = Number(settings.activeNoteMaxChars) || 6000;
  const clippedNote = note.length > maxChars
    ? `${note.slice(0, maxChars)}\n\n[Note clipped]`
    : note;

  const notePrompt = [
    `Active Obsidian note: ${file.path}`,
    "",
    clippedNote,
    ""
  ].join("\n");
  const conversationBudget = Math.max(1000, contextLimit - notePrompt.length - referencedPrompt.length);

  promptParts.push(
    notePrompt,
    referencedPrompt,
    formatConversationPrompt(prompt, conversation, conversationBudget)
  );

  return buildPromptResult(promptParts.filter(Boolean).join("\n"), contextLimit);
}

function formatConversationPrompt(prompt, conversation, maxChars) {
  if (!conversation || conversation.length <= 1) {
    return ["User request:", prompt].join("\n");
  }

  const transcript = formatConversationTranscript(conversation, maxChars);

  return [
    "Conversation so far:",
    transcript,
    "",
    "Respond to the latest user request."
  ].join("\n");
}

async function buildReferencedPathsPrompt(app, prompt, contextLimit) {
  const paths = extractMentionPaths(prompt);
  if (paths.length === 0) {
    return "";
  }

  const maxChars = Math.min(16000, Math.max(4000, Math.floor(contextLimit * 0.15)));
  const parts = ["Referenced Obsidian paths:"];
  let used = parts[0].length;

  for (const mentionPath of paths) {
    const entry = app.vault.getAbstractFileByPath(mentionPath);
    if (!entry) {
      const missing = [`Path: ${mentionPath}`, "[Not found in vault]"].join("\n");
      if (!appendReferencedPart(parts, missing, maxChars, used)) {
        break;
      }
      used += missing.length + 2;
      continue;
    }

    const part = entry.children
      ? formatReferencedFolder(entry)
      : await formatReferencedFile(app, entry);
    if (!appendReferencedPart(parts, part, maxChars, used)) {
      parts.push("[Additional referenced paths omitted]");
      break;
    }
    used += part.length + 2;
  }

  return `${parts.join("\n\n")}\n`;
}

async function formatReferencedFile(app, file) {
  const maxFileChars = 3000;
  const content = await app.vault.cachedRead(file);
  const clippedContent = content.length > maxFileChars
    ? `${content.slice(0, maxFileChars)}\n\n[Referenced file clipped]`
    : content;
  return [
    `File: ${file.path}`,
    "```",
    clippedContent,
    "```"
  ].join("\n");
}

function formatReferencedFolder(folder) {
  const maxEntries = 200;
  const paths = [];
  collectFolderPaths(folder, paths, maxEntries);
  const omitted = paths.length >= maxEntries ? "\n[Folder listing clipped]" : "";
  return [
    `Folder: ${folder.path}`,
    paths.map((path) => `- ${path}`).join("\n") + omitted
  ].filter(Boolean).join("\n");
}

function collectFolderPaths(folder, paths, maxEntries) {
  for (const child of folder.children || []) {
    if (paths.length >= maxEntries) {
      return;
    }
    paths.push(child.children ? `${child.path}/` : child.path);
    if (child.children) {
      collectFolderPaths(child, paths, maxEntries);
    }
  }
}

function appendReferencedPart(parts, part, maxChars, used) {
  if (used + part.length + 2 > maxChars) {
    return false;
  }
  parts.push(part);
  return true;
}

function extractMentionPaths(prompt) {
  const paths = [];
  const seen = new Set();
  const pattern = /@(?:"((?:\\"|[^"])*)"|([^\s]+))/g;
  let match;

  const addPath = (path) => {
    const normalizedPath = String(path || "").replace(/\\"/g, "\"").trim();
    if (normalizedPath && !seen.has(normalizedPath)) {
      seen.add(normalizedPath);
      paths.push(normalizedPath);
    }
  };

  while ((match = pattern.exec(prompt)) !== null) {
    addPath(match[1] || match[2] || "");
  }

  for (const path of extractObsidianOpenPaths(prompt)) {
    addPath(path);
  }

  return paths;
}

function extractObsidianOpenPaths(prompt) {
  const paths = [];
  const pattern = /obsidian:\/\/open\?[^\s<>"']+/g;
  let match;

  while ((match = pattern.exec(prompt)) !== null) {
    const path = extractObsidianOpenFilePath(match[0]);
    if (path) {
      paths.push(path);
    }
  }

  return paths;
}

function extractObsidianOpenFilePath(url) {
  try {
    const parsed = new URL(url);
    if (parsed.protocol !== "obsidian:" || parsed.hostname !== "open") {
      return "";
    }
    return parsed.searchParams.get("file") || "";
  } catch {
    return "";
  }
}

function formatConversationTranscript(conversation, maxChars) {
  const fullTranscript = conversation.map(formatMessageForTranscript).join("\n\n");
  if (!maxChars || fullTranscript.length <= maxChars) {
    return fullTranscript;
  }

  const latestMessage = conversation[conversation.length - 1];
  const latestText = formatMessageForTranscript(latestMessage);
  const summaryHeader = `[Earlier conversation compressed because it exceeded the context character limit. Original messages: ${conversation.length - 1}.]`;
  const availableForRecent = Math.max(0, maxChars - latestText.length - summaryHeader.length - 8);
  const recentMessages = [];
  let used = 0;

  for (let index = conversation.length - 2; index >= 0; index -= 1) {
    const formatted = formatMessageForTranscript(conversation[index]);
    const nextUsed = used + formatted.length + (recentMessages.length > 0 ? 2 : 0);
    if (nextUsed > availableForRecent) {
      break;
    }
    recentMessages.unshift(formatted);
    used = nextUsed;
  }

  const omittedCount = Math.max(0, conversation.length - 1 - recentMessages.length);
  const compressedSummary = summarizeMessages(conversation.slice(0, omittedCount), summaryHeader);
  const compressedTranscript = [
    compressedSummary,
    recentMessages.join("\n\n"),
    latestText
  ].filter(Boolean).join("\n\n");

  return limitCompressedTranscript(compressedTranscript, latestText, maxChars);
}

function summarizeMessages(messages, header) {
  if (messages.length === 0) {
    return "";
  }

  const maxSummaryChars = 12000;
  const lines = [header];
  let used = header.length;

  for (const message of messages) {
    const content = compactText(message.content);
    const line = `- ${message.role === "user" ? "User" : "Agent"}: ${truncateText(content, 500)}`;
    if (used + line.length + 1 > maxSummaryChars) {
      lines.push(`- ... ${messages.length - lines.length + 1} earlier messages omitted`);
      break;
    }
    lines.push(line);
    used += line.length + 1;
  }

  return lines.join("\n");
}

function formatMessageForTranscript(message) {
  return `${message.role === "user" ? "User" : "Agent"}: ${message.content}`;
}

function compactText(text) {
  return String(text || "").replace(/\s+/g, " ").trim();
}

function truncateText(text, maxChars) {
  if (text.length <= maxChars) {
    return text;
  }
  if (maxChars <= 3) {
    return text.slice(0, maxChars);
  }
  return `${text.slice(0, maxChars - 3)}...`;
}

function limitCompressedTranscript(transcript, latestText, maxChars) {
  if (!maxChars || transcript.length <= maxChars) {
    return transcript;
  }

  if (latestText.length >= maxChars) {
    return truncateText(latestText, maxChars);
  }

  const prefixBudget = Math.max(0, maxChars - latestText.length - 2);
  const prefix = truncateText(transcript.slice(0, transcript.length - latestText.length), prefixBudget);
  return [prefix, latestText].filter(Boolean).join("\n\n");
}

function limitPrompt(prompt, maxChars) {
  if (!maxChars || prompt.length <= maxChars) {
    return prompt;
  }

  const notice = "[Prompt compressed to fit the configured context character limit.]\n\n";
  const available = Math.max(0, maxChars - notice.length);
  if (available === 0) {
    return notice.slice(0, maxChars);
  }
  return `${notice}${prompt.slice(prompt.length - available)}`;
}

function buildPromptResult(rawPrompt, contextLimit) {
  const prompt = limitPrompt(rawPrompt, contextLimit);
  return {
    prompt,
    context: {
      limitChars: contextLimit,
      originalChars: rawPrompt.length,
      promptChars: prompt.length,
      compressed: prompt.length < rawPrompt.length || rawPrompt.includes("[Earlier conversation compressed")
    }
  };
}

module.exports = {
  buildPrompt,
  buildPromptWithMetadata
};

},
"src/settings.js": function(module, exports, __require) {
const { MODE_OPTIONS } = __require("src/modes.js");

const DEFAULT_SETTINGS = {
  agentId: "codex",
  codexPath: "/opt/homebrew/bin/codex",
  args: "exec {{prompt}}",
  interactiveArgs: "",
  mode: "readOnly",
  workingDirectory: "",
  includeActiveNote: true,
  debugActivity: false,
  activeNoteMaxChars: 6000,
  contextLimitChars: 258000
};

function normalizeSettings(savedSettings) {
  const settings = Object.assign({}, DEFAULT_SETTINGS, savedSettings || {});

  if (savedSettings && savedSettings.command && !savedSettings.codexPath) {
    settings.codexPath = savedSettings.command;
  }

  if (settings.mode === "ask") {
    settings.mode = "readOnly";
  }

  if (!MODE_OPTIONS[settings.mode]) {
    settings.mode = DEFAULT_SETTINGS.mode;
  }

  if (!settings.agentId) {
    settings.agentId = DEFAULT_SETTINGS.agentId;
  }

  settings.activeNoteMaxChars = normalizePositiveInteger(
    settings.activeNoteMaxChars,
    DEFAULT_SETTINGS.activeNoteMaxChars
  );
  settings.contextLimitChars = normalizePositiveInteger(
    settings.contextLimitChars,
    DEFAULT_SETTINGS.contextLimitChars
  );

  delete settings.command;
  return settings;
}

function normalizePositiveInteger(value, fallback) {
  const parsed = Number.parseInt(value, 10);
  return Number.isFinite(parsed) && parsed > 0 ? parsed : fallback;
}

module.exports = {
  DEFAULT_SETTINGS,
  normalizeSettings
};

},
"src/agents/codex/jsonEvents.js": function(module, exports, __require) {
function codexJsonEventToUpdates(event) {
  if (!event || typeof event !== "object") {
    return [];
  }

  const type = event.type || "event";
  const item = event.item;

  if (type === "error") {
    return [{ kind: "error", title: "Error", detail: extractText(event) || compactJson(event) }];
  }

  if (type === "thread.started") {
    return [{ kind: "activity", title: "Thread started", detail: event.thread_id || "" }];
  }

  if (type === "turn.started") {
    return [{ kind: "activity", title: "Turn started", detail: "" }];
  }

  if (type === "turn.completed") {
    return [{ kind: "activity", title: "Turn completed", detail: formatUsage(event.usage) }];
  }

  if (type === "turn.failed") {
    return [{ kind: "error", title: "Turn failed", detail: extractText(event) || compactJson(event) }];
  }

  if (!item || typeof item !== "object") {
    return [{ kind: "activity", title: type, detail: compactJson(event) }];
  }

  if (item.type === "agent_message") {
    const text = extractText(item);
    return text ? [{ kind: "content", text }] : [];
  }

  if (item.type === "reasoning") {
    return [{
      kind: "reasoning",
      title: type === "item.started" ? "Thinking..." : "Thinking",
      detail: extractText(item) || summarizeItem(item)
    }];
  }

  if (item.type === "command_execution") {
    return [{
      kind: "tool",
      title: formatCommandTitle(type, item),
      summary: formatCommandSummary(item),
      detail: formatCommandExecution(item)
    }];
  }

  if (isToolItem(item)) {
    const summary = extractText(item) || summarizeItem(item);
    return [{
      kind: "tool",
      title: formatEventTitle(type, formatToolTitle(item)),
      summary: compactOneLine(summary),
      detail: summary
    }];
  }

  if (item.type === "web_search") {
    const summary = extractText(item) || summarizeItem(item);
    return [{
      kind: "tool",
      title: formatEventTitle(type, "Web search"),
      summary: compactOneLine(summary),
      detail: summary
    }];
  }

  if (type.startsWith("item.")) {
    return [{
      kind: "activity",
      title: formatEventTitle(type, item.type || "Item"),
      detail: extractText(item) || summarizeItem(item)
    }];
  }

  return [{ kind: "activity", title: type, detail: compactJson(event) }];
}

function extractText(value) {
  if (!value || typeof value !== "object") {
    return typeof value === "string" ? value : "";
  }

  for (const key of ["text", "message", "content", "output", "result", "summary"]) {
    const candidate = value[key];
    if (typeof candidate === "string") {
      return candidate;
    }
    if (Array.isArray(candidate)) {
      const joined = candidate
        .map((entry) => typeof entry === "string" ? entry : extractText(entry))
        .filter(Boolean)
        .join("\n");
      if (joined) {
        return joined;
      }
    }
  }

  return "";
}

function isToolItem(item) {
  return [
    "tool_call",
    "mcp_tool_call",
    "function_call",
    "local_shell",
    "patch",
    "file_change"
  ].includes(item.type);
}

function formatToolTitle(item) {
  return item.name || item.tool_name || item.server_name || item.type || "Tool";
}

function formatEventTitle(eventType, label) {
  if (eventType === "item.started") {
    return `${label} started`;
  }
  if (eventType === "item.completed") {
    return `${label} completed`;
  }
  if (eventType === "item.failed") {
    return `${label} failed`;
  }
  return label;
}

function formatCommandTitle(eventType, item) {
  const command = formatCommand(item.command);
  const label = command ? `$ ${compactOneLine(command)}` : "Command";
  return formatEventTitle(eventType, label);
}

function formatCommandSummary(item) {
  const parts = [];
  const command = formatCommand(item.command);
  if (command) {
    parts.push(command);
  }
  if (item.exit_code !== undefined) {
    parts.push(`exit code: ${item.exit_code}`);
  }
  const text = extractText(item);
  if (text) {
    parts.push(compactOneLine(text));
  }
  return compactOneLine(parts.join(" | "));
}

function formatCommandExecution(item) {
  const parts = [];
  const command = formatCommand(item.command);
  if (command) {
    parts.push(`$ ${command}`);
  }
  if (item.exit_code !== undefined) {
    parts.push(`exit code: ${item.exit_code}`);
  }
  const text = extractText(item);
  if (text) {
    parts.push(text);
  }
  return parts.join("\n\n") || summarizeItem(item);
}

function formatCommand(command) {
  if (Array.isArray(command)) {
    return command.map((part) => String(part)).join(" ");
  }
  if (command === undefined || command === null) {
    return "";
  }
  return String(command);
}

function compactOneLine(text) {
  return String(text || "")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, 180);
}

function formatUsage(usage) {
  if (!usage || typeof usage !== "object") {
    return "";
  }

  const parts = [];
  for (const [key, value] of Object.entries(usage)) {
    if (typeof value === "number") {
      parts.push(`${key}: ${value}`);
    }
  }
  return parts.join(", ");
}

function summarizeItem(item) {
  const summary = {};
  for (const key of ["type", "status", "name", "tool_name", "server_name", "command", "exit_code", "path"]) {
    if (item[key] !== undefined) {
      summary[key] = item[key];
    }
  }
  return Object.keys(summary).length > 0 ? compactJson(summary) : compactJson(item);
}

function compactJson(value) {
  try {
    return JSON.stringify(value, null, 2);
  } catch {
    return String(value);
  }
}

module.exports = {
  codexJsonEventToUpdates
};

},
"src/agents/codex/CodexAgent.js": function(module, exports, __require) {
const { Notice } = require("obsidian");
const { spawn } = require("child_process");
const fs = require("fs/promises");
const os = require("os");
const path = require("path");

const { parseArgsTemplate, withJsonOutput, withOutputLastMessage } = __require("src/cli/args.js");
const { buildCliPath } = __require("src/cli/env.js");
const { escapeAppleScriptString, shellQuote } = __require("src/cli/shell.js");
const { applyModeArgs } = __require("src/modes.js");
const { buildPromptWithMetadata } = __require("src/prompt.js");
const { DEFAULT_SETTINGS } = __require("src/settings.js");
const { codexJsonEventToUpdates } = __require("src/agents/codex/jsonEvents.js");

class CodexAgent {
  constructor(plugin) {
    this.plugin = plugin;
    this.id = "codex";
    this.label = "Codex";
    this.children = new Set();
  }

  async run(prompt, onUpdate, conversation, options = {}) {
    const settings = this.plugin.settings;
    const cwd = this.getWorkingDirectory();
    const promptResult = await buildPromptWithMetadata(this.plugin.app, settings, prompt, conversation);
    const finalPrompt = promptResult.prompt;
    if (promptResult.context.compressed) {
      onUpdate({
        kind: "notice",
        title: "Context compressed",
        summary: `Compressed ${formatNumber(promptResult.context.originalChars)} chars into ${formatNumber(promptResult.context.promptChars)} / ${formatNumber(promptResult.context.limitChars)} chars.`
      });
    }
    const outputPath = path.join(
      os.tmpdir(),
      `obsidian-agent-dock-${Date.now()}-${Math.random().toString(16).slice(2)}.txt`
    );
    const args = withJsonOutput(
      withOutputLastMessage(
        applyModeArgs(
          parseArgsTemplate(settings.args, finalPrompt, DEFAULT_SETTINGS.args),
          settings.mode,
          DEFAULT_SETTINGS.mode
        ),
        outputPath
      )
    );

    return new Promise((resolve, reject) => {
      let finalOutput = "";
      let errorOutput = "";
      let stdoutBuffer = "";
      let settled = false;
      let aborted = false;

      const child = spawn(settings.codexPath, args, {
        cwd,
        shell: false,
        env: Object.assign({}, process.env, {
          PATH: buildCliPath(process.env.PATH),
          TERM: "dumb"
        }),
        stdio: ["ignore", "pipe", "pipe"]
      });
      this.children.add(child);

      const cleanup = () => {
        this.children.delete(child);
        options.signal?.removeEventListener("abort", abortRun);
      };

      const settle = (callback, value) => {
        if (settled) {
          return;
        }

        settled = true;
        cleanup();
        callback(value);
      };

      const abortRun = () => {
        aborted = true;
        child.kill("SIGTERM");
      };

      if (options.signal?.aborted) {
        abortRun();
      } else {
        options.signal?.addEventListener("abort", abortRun, { once: true });
      }

      const handleJsonLine = (line) => {
        if (!line.trim()) {
          return;
        }

        try {
          const event = JSON.parse(line);
          const updates = codexJsonEventToUpdates(event);
          for (const update of updates) {
            if (update.kind === "content") {
              finalOutput += update.text;
            }
            onUpdate(update);
          }
        } catch {
          onUpdate({ kind: "activity", title: "Raw output", detail: line });
        }
      };

      child.stdout.on("data", (data) => {
        stdoutBuffer += data.toString();
        const lines = stdoutBuffer.split(/\r?\n/);
        stdoutBuffer = lines.pop() || "";
        for (const line of lines) {
          handleJsonLine(line);
        }
      });

      child.stderr.on("data", (data) => {
        errorOutput += data.toString();
        const text = data.toString().trim();
        if (text) {
          onUpdate({ kind: "activity", title: "Codex", detail: text });
        }
      });

      child.on("error", (error) => settle(reject, error));
      child.on("close", async (code) => {
        if (stdoutBuffer.trim()) {
          handleJsonLine(stdoutBuffer);
        }

        const fileOutput = await readOutputFile(outputPath);
        if (!finalOutput.trim() && fileOutput) {
          finalOutput = fileOutput;
          onUpdate({ kind: "content", text: fileOutput });
        }

        if (aborted) {
          settle(reject, createAbortError());
          return;
        }

        if (code === 0) {
          settle(resolve, finalOutput.trim());
          return;
        }

        const details = [errorOutput.trim(), fileOutput.trim()]
          .filter(Boolean)
          .join("\n\n");
        settle(reject, new Error(details || `Codex exited with code ${code}`));
      });
    });
  }

  cancelAll() {
    for (const child of this.children) {
      child.kill("SIGTERM");
    }
    this.children.clear();
  }

  async openInteractive() {
    if (process.platform !== "darwin") {
      new Notice("Interactive Codex launch is currently implemented for macOS Terminal.");
      return;
    }

    const settings = this.plugin.settings;
    const cwd = this.getWorkingDirectory();
    const command = [
      `cd ${shellQuote(cwd)}`,
      `${shellQuote(settings.codexPath)} ${settings.interactiveArgs || ""}`.trim()
    ].join(" && ");
    const script = [
      "tell application \"Terminal\"",
      "activate",
      `do script "${escapeAppleScriptString(command)}"`,
      "end tell"
    ].join("\n");

    await new Promise((resolve, reject) => {
      const child = spawn("osascript", ["-e", script], {
        env: Object.assign({}, process.env, {
          PATH: buildCliPath(process.env.PATH)
        }),
        stdio: ["ignore", "pipe", "pipe"]
      });

      let errorOutput = "";
      child.stderr.on("data", (data) => {
        errorOutput += data.toString();
      });
      child.on("error", (error) => reject(error));
      child.on("close", (code) => {
        if (code === 0) {
          resolve();
          return;
        }

        reject(new Error(errorOutput.trim() || `Terminal exited with code ${code}`));
      });
    });
  }

  getWorkingDirectory() {
    return this.plugin.settings.workingDirectory || this.plugin.app.vault.adapter.basePath;
  }
}

async function readOutputFile(outputPath) {
  try {
    const content = await fs.readFile(outputPath, "utf8");
    await fs.unlink(outputPath).catch(() => {});
    return content;
  } catch {
    return "";
  }
}

function formatNumber(value) {
  return new Intl.NumberFormat().format(value);
}

function createAbortError() {
  const error = new Error("Codex run was stopped.");
  error.name = "AbortError";
  return error;
}

module.exports = {
  CodexAgent
};

},
"src/agents/AgentRegistry.js": function(module, exports, __require) {
const { CodexAgent } = __require("src/agents/codex/CodexAgent.js");

function createAgent(plugin) {
  switch (plugin.settings.agentId) {
    case "codex":
    default:
      return new CodexAgent(plugin);
  }
}

const AGENT_OPTIONS = {
  codex: {
    label: "Codex",
    description: "OpenAI Codex CLI"
  }
};

module.exports = {
  AGENT_OPTIONS,
  createAgent
};

},
"src/constants.js": function(module, exports, __require) {
const VIEW_TYPE_AGENT_DOCK = "codex-dock-view";

module.exports = {
  VIEW_TYPE_AGENT_DOCK
};

},
"src/settingsTab.js": function(module, exports, __require) {
const { PluginSettingTab, Setting } = require("obsidian");

const { AGENT_OPTIONS } = __require("src/agents/AgentRegistry.js");
const { DEFAULT_SETTINGS } = __require("src/settings.js");

class AgentDockSettingTab extends PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }

  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Agent Dock" });

    new Setting(containerEl)
      .setName("Agent provider")
      .setDesc("Adapter used by the dock. More providers can be added without changing the UI.")
      .addDropdown((dropdown) => {
        for (const [id, option] of Object.entries(AGENT_OPTIONS)) {
          dropdown.addOption(id, option.label);
        }
        dropdown
          .setValue(this.plugin.settings.agentId)
          .onChange(async (value) => {
            this.plugin.settings.agentId = value;
            this.plugin.refreshAgent();
            await this.plugin.saveSettings();
          });
      });

    new Setting(containerEl)
      .setName("Codex executable path")
      .setDesc("Full path to the Codex CLI executable. GUI apps often cannot find shell commands by name.")
      .addText((text) => text
        .setPlaceholder("/opt/homebrew/bin/codex")
        .setValue(this.plugin.settings.codexPath)
        .onChange(async (value) => {
          this.plugin.settings.codexPath = value.trim() || DEFAULT_SETTINGS.codexPath;
          await this.plugin.saveSettings();
        }));

    new Setting(containerEl)
      .setName("Arguments")
      .setDesc("Use {{prompt}} where the prompt should be inserted.")
      .addText((text) => text
        .setPlaceholder("exec {{prompt}}")
        .setValue(this.plugin.settings.args)
        .onChange(async (value) => {
          this.plugin.settings.args = value.trim() || DEFAULT_SETTINGS.args;
          await this.plugin.saveSettings();
        }));

    new Setting(containerEl)
      .setName("Interactive arguments")
      .setDesc("Optional arguments used when opening the full agent TUI in Terminal.")
      .addText((text) => text
        .setPlaceholder("--sandbox workspace-write")
        .setValue(this.plugin.settings.interactiveArgs)
        .onChange(async (value) => {
          this.plugin.settings.interactiveArgs = value.trim();
          await this.plugin.saveSettings();
        }));

    new Setting(containerEl)
      .setName("Working directory")
      .setDesc("Defaults to the vault folder.")
      .addText((text) => text
        .setPlaceholder("/path/to/project")
        .setValue(this.plugin.settings.workingDirectory)
        .onChange(async (value) => {
          this.plugin.settings.workingDirectory = value.trim();
          await this.plugin.saveSettings();
        }));

    new Setting(containerEl)
      .setName("Include active note")
      .setDesc("Send the current note content along with your request.")
      .addToggle((toggle) => toggle
        .setValue(this.plugin.settings.includeActiveNote)
        .onChange(async (value) => {
          this.plugin.settings.includeActiveNote = value;
          await this.plugin.saveSettings();
        }));

    new Setting(containerEl)
      .setName("Debug activity")
      .setDesc("Show streamed reasoning summaries, tool calls, command output, stderr, and raw events under each response.")
      .addToggle((toggle) => toggle
        .setValue(this.plugin.settings.debugActivity)
        .onChange(async (value) => {
          this.plugin.settings.debugActivity = value;
          await this.plugin.saveSettings();
        }));

    new Setting(containerEl)
      .setName("Active note character limit")
      .setDesc("Prevents very large notes from overwhelming the command.")
      .addText((text) => text
        .setPlaceholder(String(DEFAULT_SETTINGS.activeNoteMaxChars))
        .setValue(String(this.plugin.settings.activeNoteMaxChars))
        .onChange(async (value) => {
          const parsed = Number.parseInt(value, 10);
          this.plugin.settings.activeNoteMaxChars = Number.isFinite(parsed) && parsed > 0
            ? parsed
            : DEFAULT_SETTINGS.activeNoteMaxChars;
          await this.plugin.saveSettings();
        }));

    new Setting(containerEl)
      .setName("Context character limit")
      .setDesc("Maximum prompt size before older conversation history is compressed. Default is 258k characters.")
      .addText((text) => text
        .setPlaceholder(String(DEFAULT_SETTINGS.contextLimitChars))
        .setValue(String(this.plugin.settings.contextLimitChars))
        .onChange(async (value) => {
          const parsed = Number.parseInt(value, 10);
          this.plugin.settings.contextLimitChars = Number.isFinite(parsed) && parsed > 0
            ? parsed
            : DEFAULT_SETTINGS.contextLimitChars;
          await this.plugin.saveSettings();
        }));
  }
}

module.exports = {
  AgentDockSettingTab
};

},
"src/view/timeline.js": function(module, exports, __require) {
function shouldShowEvent(entry, debugActivity) {
  if (debugActivity) {
    return true;
  }

  return ["reasoning", "tool", "error", "notice"].includes(entry.kind);
}

function getCompletedTimelineSections(timeline, debugActivity) {
  const finalContentIndex = findLastContentIndex(timeline);

  if (finalContentIndex === -1) {
    return {
      processedEntries: timeline.filter((entry) => shouldShowEvent(entry, debugActivity)),
      finalEntry: null
    };
  }

  return {
    processedEntries: timeline.filter((entry, index) => {
      if (index === finalContentIndex) {
        return false;
      }
      return entry.kind === "content" || shouldShowEvent(entry, debugActivity);
    }),
    finalEntry: timeline[finalContentIndex]
  };
}

function appendTimelineContent(message, text) {
  const lastEntry = message.timeline[message.timeline.length - 1];
  if (lastEntry && lastEntry.kind === "content") {
    lastEntry.text += text;
    return;
  }

  message.timeline.push({ kind: "content", text });
}

function findLastContentIndex(timeline) {
  for (let index = timeline.length - 1; index >= 0; index -= 1) {
    if (timeline[index].kind === "content") {
      return index;
    }
  }
  return -1;
}

function groupLiveTimeline(timeline, debugActivity) {
  const groups = [];
  let pendingEvents = [];

  const flushPendingEvents = () => {
    if (pendingEvents.length === 0) {
      return;
    }

    groups.push({
      type: "eventGroup",
      label: getEventGroupLabel(pendingEvents),
      entries: pendingEvents
    });
    pendingEvents = [];
  };

  for (const entry of timeline) {
    if (entry.kind === "content") {
      flushPendingEvents();
      groups.push({ type: "entry", entry });
      continue;
    }

    if (debugActivity || ["reasoning", "tool", "error"].includes(entry.kind)) {
      const previous = pendingEvents[pendingEvents.length - 1];
      if (previous && previous.kind !== entry.kind) {
        flushPendingEvents();
      }
      pendingEvents.push(entry);
    }
  }

  flushPendingEvents();
  return groups;
}

function groupProcessedEntries(entries) {
  const groups = [];
  let pending = [];

  const flush = () => {
    if (pending.length === 0) {
      return;
    }

    groups.push({ type: "eventGroup", entries: pending });
    pending = [];
  };

  for (const entry of entries) {
    if (entry.kind === "content") {
      flush();
      groups.push({ type: "entry", entry });
      continue;
    }

    const previous = pending[pending.length - 1];
    if (previous && previous.kind !== entry.kind) {
      flush();
    }
    pending.push(entry);
  }

  flush();
  return groups;
}

function getEventGroupLabel(entries) {
  const hasError = entries.some((entry) => entry.kind === "error");
  if (hasError) {
    return `需要关注 ${entries.length} 项`;
  }

  const hasTool = entries.some((entry) => entry.kind === "tool");
  const hasReasoning = entries.some((entry) => entry.kind === "reasoning");
  const hasNotice = entries.some((entry) => entry.kind === "notice");
  const label = hasTool ? "工具调用" : hasReasoning ? "思考" : hasNotice ? "提示" : "活动";
  return `${label} ${entries.length} 项`;
}

module.exports = {
  appendTimelineContent,
  getCompletedTimelineSections,
  getEventGroupLabel,
  groupLiveTimeline,
  groupProcessedEntries,
  shouldShowEvent
};

},
"src/view/AgentDockView.js": function(module, exports, __require) {
const { ItemView, MarkdownRenderer, Notice, setIcon } = require("obsidian");

const { VIEW_TYPE_AGENT_DOCK } = __require("src/constants.js");
const { MODE_OPTIONS, getModeDescription } = __require("src/modes.js");
const { DEFAULT_SETTINGS } = __require("src/settings.js");
const {
  appendTimelineContent,
  getCompletedTimelineSections,
  getEventGroupLabel,
  groupLiveTimeline,
  groupProcessedEntries,
  shouldShowEvent
} = __require("src/view/timeline.js");

class AgentDockView extends ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
    this.sessions = [];
    this.activeSessionId = "";
  }

  getViewType() {
    return VIEW_TYPE_AGENT_DOCK;
  }

  getDisplayText() {
    return "Agent Dock";
  }

  getIcon() {
    return "bot";
  }

  async onOpen() {
    this.ensureActiveSession();
    this.render();
  }

  async onClose() {
    this.cancelRunningSessions();
  }

  render() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.addClass("codex-dock");

    const header = containerEl.createDiv({ cls: "codex-dock__header" });
    header.createDiv({ cls: "codex-dock__title", text: this.plugin.agent.label });

    const actions = header.createDiv({ cls: "codex-dock__actions" });
    const terminalButton = actions.createEl("button", {
      cls: "codex-dock__icon-button",
      attr: { "aria-label": "Open interactive agent in Terminal", title: "Open interactive agent in Terminal" }
    });
    terminalButton.setText("Terminal");
    terminalButton.addEventListener("click", async () => {
      try {
        await this.plugin.openInteractiveAgent();
      } catch (error) {
        new Notice(`Could not open Terminal: ${error.message}`);
      }
    });

    this.sessionBarEl = containerEl.createDiv({ cls: "codex-dock__session-bar" });
    this.renderSessionSwitcher();

    this.messageList = containerEl.createDiv({ cls: "codex-dock__messages" });
    this.renderMessages();

    const composer = containerEl.createDiv({ cls: "codex-dock__composer" });
    this.renderComposerContent(composer, this.getActiveSession()?.draft || "");
  }

  renderSessionSwitcher() {
    if (!this.sessionBarEl) {
      return;
    }

    this.sessionBarEl.empty();
    const activeSession = this.ensureActiveSession();
    const switcher = this.sessionBarEl.createEl("details", { cls: "codex-dock__conversation-switcher" });
    const summary = switcher.createEl("summary", {
      cls: "codex-dock__conversation-summary",
      attr: {
        "aria-label": "Switch conversation",
        title: "Switch conversation"
      }
    });
    summary.createSpan({ cls: "codex-dock__conversation-title", text: activeSession.title });
    const chevron = summary.createSpan({ cls: "codex-dock__conversation-chevron", attr: { "aria-hidden": "true" } });
    setIcon(chevron, "chevron-down");

    const menu = switcher.createDiv({ cls: "codex-dock__conversation-menu" });
    menu.createDiv({ cls: "codex-dock__conversation-menu-title", text: "Conversations" });
    const list = menu.createDiv({ cls: "codex-dock__conversation-list" });
    for (const session of this.sessions) {
      const item = list.createDiv({
        cls: `codex-dock__conversation-item${session.id === this.activeSessionId ? " is-active" : ""}`
      });
      const switchButton = item.createEl("button", {
        cls: "codex-dock__conversation-item-main",
        attr: {
          type: "button",
          title: session.title
        }
      });
      const check = switchButton.createSpan({ cls: "codex-dock__conversation-check", attr: { "aria-hidden": "true" } });
      if (session.id === this.activeSessionId) {
        setIcon(check, "check");
      }
      switchButton.createSpan({ cls: "codex-dock__conversation-item-title", text: session.title });
      switchButton.addEventListener("click", () => {
        this.activeSessionId = session.id;
        switcher.removeAttribute("open");
        this.render();
      });

      const deleteButton = item.createEl("button", {
        cls: "codex-dock__conversation-delete",
        attr: {
          type: "button",
          "aria-label": `Delete ${session.title}`,
          title: "Delete conversation"
        }
      });
      setIcon(deleteButton, "trash-2");
      deleteButton.addEventListener("click", (event) => {
        event.preventDefault();
        event.stopPropagation();
        this.deleteSession(session.id);
      });
    }

    const newSessionButton = this.sessionBarEl.createEl("button", {
      cls: "codex-dock__conversation-new",
      attr: {
        type: "button",
        "aria-label": "New conversation",
        title: "New conversation"
      }
    });
    setIcon(newSessionButton, "plus");
    newSessionButton.addEventListener("click", () => {
      this.createSession();
      this.render();
    });

    const closeConversationMenu = (event) => {
      if (!switcher.contains(event.target)) {
        switcher.removeAttribute("open");
        document.removeEventListener("pointerdown", closeConversationMenu);
      }
    };
    switcher.addEventListener("toggle", () => {
      if (switcher.open) {
        window.setTimeout(() => document.addEventListener("pointerdown", closeConversationMenu), 0);
      } else {
        document.removeEventListener("pointerdown", closeConversationMenu);
      }
    });
  }

  renderComposerContent(composer, draft) {
    const shell = composer.createDiv({ cls: "codex-dock__composer-shell" });
    this.inputEl = shell.createEl("textarea", {
      cls: "codex-dock__input",
      attr: {
        rows: "4",
        placeholder: "Ask the agent about this vault or the active note..."
      }
    });
    this.inputEl.value = draft || "";
    this.mentionMenuEl = shell.createDiv({ cls: "codex-dock__mention-menu" });
    this.mentionState = {
      active: false,
      start: -1,
      end: -1,
      selectedIndex: 0,
      suggestions: []
    };

    this.inputEl.addEventListener("keydown", (event) => {
      if (this.handleMentionKeydown(event)) {
        return;
      }
      if (event.key === "Enter" && (event.metaKey || event.ctrlKey)) {
        event.preventDefault();
        this.submit();
      }
    });
    this.inputEl.addEventListener("input", () => {
      if (this.replaceObsidianLinksInInput()) {
        return;
      }
      const session = this.getActiveSession();
      if (session) {
        session.draft = this.inputEl.value;
      }
      this.updateContextStatus();
      this.updateMentionSuggestions();
    });
    this.inputEl.addEventListener("click", () => this.updateMentionSuggestions());
    this.inputEl.addEventListener("blur", () => {
      window.setTimeout(() => this.hideMentionSuggestions(), 120);
    });
    this.inputEl.addEventListener("paste", () => {
      window.setTimeout(() => this.replaceObsidianLinksInInput(), 0);
    });

    const composerBar = shell.createDiv({ cls: "codex-dock__composer-bar" });
    const leftTools = composerBar.createDiv({ cls: "codex-dock__composer-tools" });
    const activeNoteButton = leftTools.createEl("button", {
      cls: "codex-dock__composer-icon-button",
      attr: {
        type: "button",
        "aria-label": "Toggle active note context",
        title: "Toggle active note context"
      }
    });
    setIcon(activeNoteButton, "plus");
    activeNoteButton.toggleClass("is-active", this.plugin.settings.includeActiveNote);
    activeNoteButton.addEventListener("click", async () => {
      this.plugin.settings.includeActiveNote = !this.plugin.settings.includeActiveNote;
      activeNoteButton.toggleClass("is-active", this.plugin.settings.includeActiveNote);
      await this.plugin.saveSettings();
      this.updateContextStatus();
    });

    const modePill = leftTools.createEl("details", { cls: "codex-dock__mode-pill" });
    const modeSummary = modePill.createEl("summary", {
      cls: "codex-dock__mode-summary",
      attr: {
        "aria-label": "Mode",
        title: getModeDescription(this.plugin.settings.mode, DEFAULT_SETTINGS.mode)
      }
    });
    const modeIcon = modeSummary.createSpan({ cls: "codex-dock__mode-icon", attr: { "aria-hidden": "true" } });
    setIcon(modeIcon, "shield");
    const modeLabel = modeSummary.createSpan({
      cls: "codex-dock__mode-label",
      text: getModeLabel(this.plugin.settings.mode)
    });
    const modeChevron = modeSummary.createSpan({ cls: "codex-dock__mode-chevron", attr: { "aria-hidden": "true" } });
    setIcon(modeChevron, "chevron-down");

    const modeMenu = modePill.createDiv({ cls: "codex-dock__mode-menu", attr: { role: "menu" } });
    const closeModeMenu = (event) => {
      if (!modePill.contains(event.target)) {
        modePill.removeAttribute("open");
        document.removeEventListener("pointerdown", closeModeMenu);
      }
    };
    modePill.addEventListener("toggle", () => {
      if (modePill.open) {
        window.setTimeout(() => document.addEventListener("pointerdown", closeModeMenu), 0);
      } else {
        document.removeEventListener("pointerdown", closeModeMenu);
      }
    });
    for (const [value, option] of Object.entries(MODE_OPTIONS)) {
      const optionButton = modeMenu.createEl("button", {
        cls: "codex-dock__mode-option",
        text: option.label,
        attr: {
          type: "button",
          role: "menuitemradio",
          "aria-checked": String(value === this.plugin.settings.mode),
          title: option.description
        }
      });
      optionButton.toggleClass("is-selected", value === this.plugin.settings.mode);
      optionButton.addEventListener("click", async () => {
        this.plugin.settings.mode = value;
        modeLabel.setText(option.label);
        modeSummary.setAttr("title", option.description);
        for (const button of modeMenu.querySelectorAll(".codex-dock__mode-option")) {
          const isSelected = button === optionButton;
          button.classList.toggle("is-selected", isSelected);
          button.setAttribute("aria-checked", String(isSelected));
        }
        modePill.removeAttribute("open");
        await this.plugin.saveSettings();
        this.updateContextStatus();
      });
    }

    const rightTools = composerBar.createDiv({ cls: "codex-dock__composer-status" });
    this.contextStatusEl = rightTools.createDiv({ cls: "codex-dock__context-status" });
    this.updateContextStatus();

    const sendButton = rightTools.createEl("button", {
      cls: "codex-dock__send",
      attr: { type: "button" }
    });
    if (this.getActiveSession()?.currentRun) {
      sendButton.setAttr("aria-label", "Stop agent");
      sendButton.setAttr("title", "Stop agent");
      setIcon(sendButton, "square");
      sendButton.addEventListener("click", () => this.cancelActiveSession());
    } else {
      sendButton.setAttr("aria-label", "Send message");
      sendButton.setAttr("title", "Send message");
      setIcon(sendButton, "arrow-up");
      sendButton.addEventListener("click", () => this.submit());
    }
  }

  renderMessages() {
    this.messageList.empty();
    const session = this.ensureActiveSession();
    const messages = session.messages;

    if (messages.length === 0) {
      const empty = this.messageList.createDiv({ cls: "codex-dock__empty" });
      empty.createDiv({ text: "Open a side conversation with an agent." });
      empty.createDiv({ text: "The active note can be included automatically." });
      this.updateContextStatus();
      return;
    }

    for (const message of messages) {
      const item = this.messageList.createDiv({
        cls: `codex-dock__message codex-dock__message--${message.role}`
      });
      item.createDiv({
        cls: "codex-dock__role",
        text: message.role === "user" ? "You" : this.plugin.agent.label
      });
      if (message.timeline && message.timeline.length > 0) {
        const timeline = item.createDiv({ cls: "codex-dock__timeline" });
        this.renderTimeline(timeline, message);
      } else if (message.content) {
        this.renderMarkdownContent(item, message.content);
      }
      if (message.isLoading) {
        const loading = item.createDiv({ cls: "codex-dock__loading" });
        const dots = loading.createSpan({ cls: "codex-dock__loading-dots", attr: { "aria-hidden": "true" } });
        dots.createSpan();
        dots.createSpan();
        dots.createSpan();
      }
    }

    this.messageList.scrollTop = this.messageList.scrollHeight;
    this.updateContextStatus();
  }

  handleMentionKeydown(event) {
    if (!this.mentionState?.active) {
      return false;
    }

    if (event.key === "ArrowDown") {
      event.preventDefault();
      this.mentionState.selectedIndex = Math.min(
        this.mentionState.selectedIndex + 1,
        this.mentionState.suggestions.length - 1
      );
      this.updateMentionSelection({ scrollIntoView: true });
      return true;
    }

    if (event.key === "ArrowUp") {
      event.preventDefault();
      this.mentionState.selectedIndex = Math.max(this.mentionState.selectedIndex - 1, 0);
      this.updateMentionSelection({ scrollIntoView: true });
      return true;
    }

    if (event.key === "Enter" || event.key === "Tab") {
      event.preventDefault();
      this.selectMentionSuggestion(this.mentionState.selectedIndex);
      return true;
    }

    if (event.key === "Escape") {
      event.preventDefault();
      this.hideMentionSuggestions();
      return true;
    }

    return false;
  }

  updateMentionSuggestions() {
    const match = getMentionMatch(this.inputEl.value, this.inputEl.selectionStart);
    if (!match) {
      this.hideMentionSuggestions();
      return;
    }

    const suggestions = this.getVaultPathSuggestions(match.query);
    if (suggestions.length === 0) {
      this.hideMentionSuggestions();
      return;
    }

    this.mentionState = {
      active: true,
      start: match.start,
      end: match.end,
      selectedIndex: 0,
      suggestions
    };
    this.renderMentionSuggestions();
  }

  getVaultPathSuggestions(query) {
    const normalizedQuery = query.toLowerCase();
    return this.app.vault.getAllLoadedFiles()
      .map((entry) => ({
        path: entry.path,
        name: entry.name || entry.path,
        folder: getParentPath(entry.path),
        kind: entry.children ? "folder" : "file"
      }))
      .filter((entry) => entry.path)
      .filter((entry) => {
        if (!normalizedQuery) {
          return true;
        }
        return entry.path.toLowerCase().includes(normalizedQuery);
      })
      .sort((left, right) => {
        if (left.kind !== right.kind) {
          return left.kind === "file" ? -1 : 1;
        }
        return left.path.localeCompare(right.path);
      })
      .slice(0, 7);
  }

  renderMentionSuggestions() {
    if (!this.mentionMenuEl || !this.mentionState.active) {
      return;
    }

    this.mentionMenuEl.empty();
    this.mentionMenuEl.addClass("is-open");
    const list = this.mentionMenuEl.createDiv({ cls: "codex-dock__mention-list" });
    for (let index = 0; index < this.mentionState.suggestions.length; index += 1) {
      const suggestion = this.mentionState.suggestions[index];
      const option = list.createEl("button", {
        cls: `codex-dock__mention-option${index === this.mentionState.selectedIndex ? " is-selected" : ""}`,
        attr: {
          type: "button",
          title: suggestion.path
        }
      });
      const icon = option.createSpan({ cls: "codex-dock__mention-icon", attr: { "aria-hidden": "true" } });
      setIcon(icon, suggestion.kind === "folder" ? "folder" : "file-text");
      const text = option.createSpan({ cls: "codex-dock__mention-text" });
      text.createSpan({ cls: "codex-dock__mention-name", text: suggestion.name });
      text.createSpan({
        cls: "codex-dock__mention-path",
        text: suggestion.kind === "folder" ? "Folder" : suggestion.folder || "Vault root"
      });
      option.addEventListener("mousedown", (event) => {
        event.preventDefault();
        this.selectMentionSuggestion(index);
      });
      option.addEventListener("mouseenter", () => {
        if (this.mentionState.selectedIndex === index) {
          return;
        }
        this.mentionState.selectedIndex = index;
        this.updateMentionSelection();
      });
    }

    this.renderMentionPreview();
  }

  updateMentionSelection(options = {}) {
    if (!this.mentionMenuEl || !this.mentionState.active) {
      return;
    }

    const optionEls = this.mentionMenuEl.querySelectorAll(".codex-dock__mention-option");
    for (let index = 0; index < optionEls.length; index += 1) {
      const isSelected = index === this.mentionState.selectedIndex;
      optionEls[index].classList.toggle("is-selected", isSelected);
      if (isSelected && options.scrollIntoView) {
        optionEls[index].scrollIntoView({ block: "nearest" });
      }
    }
    this.renderMentionPreview();
  }

  renderMentionPreview() {
    if (!this.mentionMenuEl || !this.mentionState.active) {
      return;
    }

    this.mentionMenuEl.querySelector(".codex-dock__mention-preview")?.remove();
    const selected = this.mentionState.suggestions[this.mentionState.selectedIndex];
    if (selected) {
      const preview = this.mentionMenuEl.createDiv({ cls: "codex-dock__mention-preview" });
      const segments = selected.path.split("/");
      for (let index = 0; index < segments.length; index += 1) {
        const segment = segments[index];
        const row = preview.createDiv({
          cls: `codex-dock__mention-preview-row depth-${Math.min(index, 4)}`
        });
        const icon = row.createSpan({ cls: "codex-dock__mention-preview-icon", attr: { "aria-hidden": "true" } });
        setIcon(icon, index === segments.length - 1 && selected.kind === "file" ? "file-text" : "folder");
        row.createSpan({ cls: "codex-dock__mention-preview-name", text: segment });
      }
    }
  }

  selectMentionSuggestion(index) {
    const suggestion = this.mentionState?.suggestions[index];
    if (!suggestion) {
      return;
    }

    const value = this.inputEl.value;
    const mention = formatMentionToken(suggestion.path);
    const nextValue = `${value.slice(0, this.mentionState.start)}${mention} ${value.slice(this.mentionState.end)}`;
    const nextCursor = this.mentionState.start + mention.length + 1;
    this.inputEl.value = nextValue;
    this.inputEl.selectionStart = nextCursor;
    this.inputEl.selectionEnd = nextCursor;
    const session = this.getActiveSession();
    if (session) {
      session.draft = nextValue;
    }
    this.hideMentionSuggestions();
    this.updateContextStatus();
    this.inputEl.focus();
  }

  hideMentionSuggestions() {
    if (!this.mentionMenuEl) {
      return;
    }

    this.mentionState = {
      active: false,
      start: -1,
      end: -1,
      selectedIndex: 0,
      suggestions: []
    };
    this.mentionMenuEl.empty();
    this.mentionMenuEl.removeClass("is-open");
  }

  replaceObsidianLinksInInput() {
    const value = this.inputEl.value;
    const nextValue = replaceObsidianOpenLinks(value);
    if (nextValue === value) {
      return false;
    }

    const cursor = this.inputEl.selectionStart;
    const delta = nextValue.length - value.length;
    this.inputEl.value = nextValue;
    this.inputEl.selectionStart = Math.max(0, cursor + delta);
    this.inputEl.selectionEnd = this.inputEl.selectionStart;
    const session = this.getActiveSession();
    if (session) {
      session.draft = nextValue;
    }
    this.updateContextStatus();
    this.updateMentionSuggestions();
    return true;
  }

  async submit() {
    const session = this.ensureActiveSession();
    if (session.currentRun) {
      new Notice(`${this.plugin.agent.label} is still working in this conversation.`);
      return;
    }

    const prompt = this.inputEl.value.trim();
    if (!prompt) {
      return;
    }

    this.maybeNameSession(session, prompt);
    this.updateSessionSwitcher();
    this.inputEl.value = "";
    session.draft = "";
    session.messages.push({
      role: "user",
      content: prompt,
      timeline: [{ kind: "message", text: prompt }]
    });
    const assistantMessage = { role: "assistant", content: "", timeline: [], isLoading: true };
    session.messages.push(assistantMessage);
    const run = {
      abortController: new AbortController(),
      assistantMessage
    };
    session.currentRun = run;
    this.renderMessages();
    this.renderComposer();

    try {
      const conversation = session.messages.slice(0, -1);
      await this.plugin.runAgent(prompt, (update) => {
        if (assistantMessage.isComplete || session.currentRun !== run) {
          return;
        }

        if (update.kind === "content") {
          assistantMessage.content += update.text;
          appendTimelineContent(assistantMessage, update.text);
        } else {
          assistantMessage.timeline.push(update);
        }
        this.renderSessionIfActive(session);
      }, conversation, { signal: run.abortController.signal });

      assistantMessage.isLoading = false;
      assistantMessage.isComplete = true;
      if (!assistantMessage.content.trim()) {
        const emptyText = `(${this.plugin.agent.label} finished without text output.)`;
        assistantMessage.content = emptyText;
        appendTimelineContent(assistantMessage, emptyText);
      }
      this.renderSessionIfActive(session);
    } catch (error) {
      assistantMessage.isLoading = false;
      assistantMessage.isComplete = true;
      const errorText = error.name === "AbortError"
        ? `(${this.plugin.agent.label} stopped.)`
        : [
            `${this.plugin.agent.label} could not run.`,
            "",
            error.message,
            "",
            "Check the executable path in plugin settings and make sure the CLI is installed and allowed by macOS."
          ].join("\n");
      assistantMessage.content = errorText;
      appendTimelineContent(assistantMessage, errorText);
      this.renderSessionIfActive(session);
      if (error.name === "AbortError") {
        new Notice(`${this.plugin.agent.label} stopped.`);
      } else {
        new Notice(`${this.plugin.agent.label} command failed.`);
      }
    } finally {
      if (session.currentRun === run) {
        session.currentRun = null;
      }
      this.renderSessionIfActive(session);
      this.renderComposerIfActive(session);
    }
  }

  renderComposer() {
    const composer = this.containerEl.querySelector(".codex-dock__composer");
    if (!composer) {
      return;
    }

    const draft = this.inputEl?.value || "";
    composer.empty();
    this.renderComposerContent(composer, draft);
  }

  renderTimeline(containerEl, message) {
    if (message.role !== "assistant") {
      for (const entry of message.timeline) {
        this.renderTimelineEntry(containerEl, entry);
      }
      return;
    }

    if (message.isComplete) {
      this.renderCompletedTimeline(containerEl, message.timeline);
      return;
    }

    for (const group of groupLiveTimeline(message.timeline, this.plugin.settings.debugActivity)) {
      if (group.type === "eventGroup") {
        this.renderEventGroup(containerEl, group.entries, group.label, false);
      } else {
        this.renderTimelineEntry(containerEl, group.entry);
      }
    }
  }

  renderCompletedTimeline(containerEl, timeline) {
    const { processedEntries, finalEntry } = getCompletedTimelineSections(
      timeline,
      this.plugin.settings.debugActivity
    );

    if (processedEntries.length > 0) {
      this.renderProcessedGroup(containerEl, processedEntries);
    }

    if (finalEntry) {
      this.renderTimelineEntry(containerEl, finalEntry);
    }
  }

  renderProcessedGroup(containerEl, entries) {
    if (entries.length === 0) {
      return;
    }

    const details = containerEl.createEl("details", {
      cls: "codex-dock__event-group codex-dock__event-group--processed"
    });
    details.open = false;
    details.createEl("summary", {
      cls: "codex-dock__event-group-summary",
      text: `已处理 ${entries.length} 项`
    });

    const body = details.createDiv({ cls: "codex-dock__event-group-body" });
    for (const group of groupProcessedEntries(entries)) {
      if (group.type === "eventGroup") {
        this.renderEventGroup(body, group.entries, getEventGroupLabel(group.entries), false);
      } else {
        this.renderTimelineEntry(body, group.entry);
      }
    }
  }

  renderEventGroup(containerEl, entries, label, open) {
    const details = containerEl.createEl("details", {
      cls: "codex-dock__event-group"
    });
    details.open = open;
    details.createEl("summary", {
      cls: "codex-dock__event-group-summary",
      text: label
    });

    const body = details.createDiv({ cls: "codex-dock__event-group-body" });
    for (const entry of entries) {
      this.renderTimelineEntry(body, entry, { forceDetail: this.plugin.settings.debugActivity });
    }
  }

  renderTimelineEntry(containerEl, entry) {
    if (entry.kind === "message" || entry.kind === "content") {
      this.renderMarkdownContent(containerEl, entry.text);
      return;
    }

    if (!this.shouldShowEvent(entry)) {
      return;
    }

    const eventEl = containerEl.createDiv({ cls: `codex-dock__event codex-dock__event--${entry.kind || "activity"}` });
    eventEl.createDiv({ cls: "codex-dock__event-title", text: entry.title || "Event" });
    if (entry.summary && !this.plugin.settings.debugActivity) {
      eventEl.createDiv({ cls: "codex-dock__event-summary", text: entry.summary });
    }
    if (entry.detail && this.plugin.settings.debugActivity) {
      eventEl.createEl("pre", { cls: "codex-dock__event-detail", text: entry.detail });
    }
  }

  renderMarkdownContent(containerEl, text) {
    const contentEl = containerEl.createDiv({ cls: "codex-dock__content markdown-rendered" });
    const copyButton = contentEl.createEl("button", {
      cls: "codex-dock__copy-button",
      text: "Copy",
      attr: {
        type: "button",
        "aria-label": "Copy message text",
        title: "Copy message text"
      }
    });
    copyButton.addEventListener("click", async (event) => {
      event.preventDefault();
      event.stopPropagation();
      await copyText(text || "");
      copyButton.setText("Copied");
      window.setTimeout(() => copyButton.setText("Copy"), 1200);
    });

    const markdownEl = contentEl.createDiv({ cls: "codex-dock__content-body" });
    const sourcePath = this.app.workspace.getActiveFile()?.path || "";
    MarkdownRenderer.render(this.app, text || "", markdownEl, sourcePath, this).catch(() => {
      markdownEl.setText(text || "");
    });
  }

  shouldShowEvent(entry) {
    return shouldShowEvent(entry, this.plugin.settings.debugActivity);
  }

  updateContextStatus() {
    if (!this.contextStatusEl) {
      return;
    }

    const session = this.getActiveSession();
    const limit = Number(this.plugin.settings.contextLimitChars) || DEFAULT_SETTINGS.contextLimitChars;
    const used = estimateContextChars(session?.messages || [], this.inputEl?.value || "", this.plugin.settings);
    const percent = Math.min(999, Math.round((used / limit) * 100));
    this.contextStatusEl.toggleClass("is-warning", percent >= 80);
    this.contextStatusEl.toggleClass("is-over", percent >= 100);
    this.contextStatusEl.setText(`${percent}%`);
    this.contextStatusEl.setAttr(
      "title",
      `Context ${percent}% · ${formatCompactNumber(used)} / ${formatCompactNumber(limit)} chars`
    );
  }

  ensureActiveSession() {
    if (this.sessions.length === 0) {
      return this.createSession();
    }

    const existing = this.getActiveSession();
    if (existing) {
      return existing;
    }

    this.activeSessionId = this.sessions[0].id;
    return this.sessions[0];
  }

  createSession() {
    const session = {
      id: `session-${Date.now()}-${Math.random().toString(16).slice(2)}`,
      title: `Chat ${this.sessions.length + 1}`,
      isUntitled: true,
      currentRun: null,
      draft: "",
      messages: []
    };
    this.sessions.push(session);
    this.activeSessionId = session.id;
    return session;
  }

  getActiveSession() {
    return this.sessions.find((session) => session.id === this.activeSessionId) || null;
  }

  maybeNameSession(session, prompt) {
    if (!session.isUntitled) {
      return;
    }

    const compact = prompt.replace(/\s+/g, " ").trim();
    session.title = compact.length > 28 ? `${compact.slice(0, 28)}...` : compact || session.title;
    session.isUntitled = false;
  }

  updateSessionSwitcher() {
    this.renderSessionSwitcher();
  }

  deleteSession(sessionId) {
    const session = this.sessions.find((entry) => entry.id === sessionId);
    if (!session) {
      return;
    }

    if (session.currentRun) {
      new Notice("Stop this conversation before deleting it.");
      return;
    }

    if (!window.confirm(`Delete "${session.title}"?`)) {
      return;
    }

    const deletedIndex = this.sessions.findIndex((entry) => entry.id === sessionId);
    this.sessions.splice(deletedIndex, 1);

    if (this.sessions.length === 0) {
      this.createSession();
    } else if (this.activeSessionId === sessionId) {
      const nextIndex = Math.min(deletedIndex, this.sessions.length - 1);
      this.activeSessionId = this.sessions[nextIndex].id;
    }

    this.render();
  }

  cancelActiveSession() {
    const session = this.getActiveSession();
    if (!session?.currentRun) {
      return;
    }

    session.currentRun.abortController.abort();
  }

  cancelRunningSessions() {
    for (const session of this.sessions) {
      if (session.currentRun) {
        session.currentRun.abortController.abort();
      }
    }
  }

  renderSessionIfActive(session) {
    if (session.id === this.activeSessionId) {
      this.renderMessages();
    }
  }

  renderComposerIfActive(session) {
    if (session.id === this.activeSessionId) {
      this.renderComposer();
    }
  }
}

function estimateContextChars(messages, draft, settings) {
  const transcriptChars = messages.reduce((total, message) => {
    return total + String(message.content || "").length + 16;
  }, 0);
  const draftChars = String(draft || "").length + 16;
  const noteChars = settings.includeActiveNote
    ? (Number(settings.activeNoteMaxChars) || DEFAULT_SETTINGS.activeNoteMaxChars)
    : 0;
  return transcriptChars + draftChars + noteChars;
}

function formatCompactNumber(value) {
  if (value >= 1000) {
    return `${Math.round(value / 1000)}k`;
  }
  return String(value);
}

function getModeLabel(mode) {
  return (MODE_OPTIONS[mode] || MODE_OPTIONS[DEFAULT_SETTINGS.mode]).label;
}

function getMentionMatch(value, cursor) {
  const beforeCursor = value.slice(0, cursor);
  const match = /(^|\s)@([^\s@]*)$/.exec(beforeCursor);
  if (!match) {
    return null;
  }

  const start = beforeCursor.length - match[2].length - 1;
  return {
    start,
    end: cursor,
    query: match[2]
  };
}

function formatMentionToken(path) {
  return /\s/.test(path) ? `@"${path.replace(/"/g, "\\\"")}"` : `@${path}`;
}

function getParentPath(path) {
  const index = path.lastIndexOf("/");
  return index >= 0 ? path.slice(0, index) : "";
}

function replaceObsidianOpenLinks(value) {
  return value.replace(/obsidian:\/\/open\?[^\s<>"']+/g, (url) => {
    const filePath = extractObsidianOpenFilePath(url);
    return filePath ? formatMentionToken(filePath) : url;
  });
}

function extractObsidianOpenFilePath(url) {
  try {
    const parsed = new URL(url);
    if (parsed.protocol !== "obsidian:" || parsed.hostname !== "open") {
      return "";
    }
    return parsed.searchParams.get("file") || "";
  } catch {
    return "";
  }
}

async function copyText(text) {
  if (navigator.clipboard?.writeText) {
    await navigator.clipboard.writeText(text);
    return;
  }

  const textarea = document.createElement("textarea");
  textarea.value = text;
  textarea.style.position = "fixed";
  textarea.style.opacity = "0";
  document.body.appendChild(textarea);
  textarea.select();
  document.execCommand("copy");
  textarea.remove();
}

module.exports = {
  AgentDockView
};

},
"src/plugin.js": function(module, exports, __require) {
const { Plugin } = require("obsidian");

const { createAgent } = __require("src/agents/AgentRegistry.js");
const { VIEW_TYPE_AGENT_DOCK } = __require("src/constants.js");
const { normalizeSettings } = __require("src/settings.js");
const { AgentDockSettingTab } = __require("src/settingsTab.js");
const { AgentDockView } = __require("src/view/AgentDockView.js");

module.exports = class AgentDockPlugin extends Plugin {
  async onload() {
    this.settings = normalizeSettings(await this.loadData());
    this.refreshAgent();

    this.registerView(
      VIEW_TYPE_AGENT_DOCK,
      (leaf) => new AgentDockView(leaf, this)
    );

    this.addRibbonIcon("bot", "Open Agent Dock", () => this.activateView());
    this.addCommand({
      id: "open-agent-dock",
      name: "Open Agent Dock",
      callback: () => this.activateView()
    });
    this.addCommand({
      id: "open-interactive-agent",
      name: "Open interactive agent in Terminal",
      callback: () => this.openInteractiveAgent()
    });

    this.addSettingTab(new AgentDockSettingTab(this.app, this));
  }

  async onunload() {
    this.agent?.cancelAll?.();
    this.app.workspace.detachLeavesOfType(VIEW_TYPE_AGENT_DOCK);
  }

  refreshAgent() {
    this.agent = createAgent(this);
  }

  async saveSettings() {
    await this.saveData(this.settings);
  }

  async activateView() {
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_AGENT_DOCK);
    let leaf = leaves[0];

    if (!leaf) {
      leaf = this.app.workspace.getRightLeaf(false);
      await leaf.setViewState({ type: VIEW_TYPE_AGENT_DOCK, active: true });
    }

    this.app.workspace.revealLeaf(leaf);
  }

  async runAgent(prompt, onUpdate, conversation, options) {
    return this.agent.run(prompt, onUpdate, conversation, options);
  }

  async openInteractiveAgent() {
    return this.agent.openInteractive();
  }
};

}
};

const __cache = {};
function __require(id) {
  if (!__modules[id]) {
    return require(id);
  }

  if (__cache[id]) {
    return __cache[id].exports;
  }

  const module = { exports: {} };
  __cache[id] = module;
  __modules[id](module, module.exports, __require);
  return module.exports;
}

module.exports = __require("src/plugin.js");
