const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const entry = "src/plugin.js";
const modules = new Map();

function resolveModule(fromId, request) {
  if (!request.startsWith(".")) {
    return null;
  }

  const fromDir = path.dirname(fromId);
  const base = path.normalize(path.join(fromDir, request));
  const candidates = [
    base,
    `${base}.js`,
    path.join(base, "index.js")
  ];

  for (const candidate of candidates) {
    const absolute = path.join(root, candidate);
    if (fs.existsSync(absolute) && fs.statSync(absolute).isFile()) {
      return candidate.replace(/\\/g, "/");
    }
  }

  throw new Error(`Could not resolve ${request} from ${fromId}`);
}

function collect(id) {
  if (modules.has(id)) {
    return;
  }

  const absolute = path.join(root, id);
  let source = fs.readFileSync(absolute, "utf8");

  source = source.replace(/require\((["'])([^"']+)\1\)/g, (match, quote, request) => {
    const resolved = resolveModule(id, request);
    if (!resolved) {
      return match;
    }
    collect(resolved);
    return `__require(${JSON.stringify(resolved)})`;
  });

  modules.set(id, source);
}

collect(entry);

const output = `// Generated by scripts/build-main.js. Edit src/ files instead.
const __modules = {
${Array.from(modules.entries()).map(([id, source]) => {
  return `${JSON.stringify(id)}: function(module, exports, __require) {
${source}
}`;
}).join(",\n")}
};

const __cache = {};
function __require(id) {
  if (!__modules[id]) {
    return require(id);
  }

  if (__cache[id]) {
    return __cache[id].exports;
  }

  const module = { exports: {} };
  __cache[id] = module;
  __modules[id](module, module.exports, __require);
  return module.exports;
}

module.exports = __require(${JSON.stringify(entry)});
`;

fs.writeFileSync(path.join(root, "main.js"), output);
